import test from 'node:test';
import assert from 'node:assert/strict';
import {assessLifecycle} from '../src/services/lifecycle.service.js';
import {catalogVerificationStatus,matchLifecycleCatalog,normalizeLifecycleCatalog} from '../src/services/lifecycle-catalog.service.js';
import {evaluateLifecycleAsset} from '../src/services/cmdb-lifecycle.service.js';

const now=new Date('2026-08-03T12:00:00Z');
const base={criticality:'medium',warrantyUntil:null,supportUntil:null,licenseUntil:null,device:{vulnerabilityFindings:[]}};
test('classifica vencimento e cadastro incompleto do ciclo de vida',()=>{assert.equal(assessLifecycle(base,now).status,'unknown');assert.equal(assessLifecycle({...base,supportUntil:new Date('2026-08-01T12:00:00Z')},now).status,'expired');assert.equal(assessLifecycle({...base,supportUntil:new Date('2026-08-25T12:00:00Z')},now).status,'warning');});
test('vulnerabilidade crítica aumenta o risco consolidado',()=>{const healthy=assessLifecycle({...base,supportUntil:new Date('2027-08-03T12:00:00Z')},now),exposed=assessLifecycle({...base,criticality:'critical',supportUntil:new Date('2027-08-03T12:00:00Z'),device:{vulnerabilityFindings:[{severity:'critical',knownExploited:true}]}},now);assert.equal(healthy.status,'healthy');assert.ok(exposed.riskScore>healthy.riskScore);assert.equal(exposed.vulnerabilities.critical,1);});
test('catálogo exige uma fonte oficial HTTPS',()=>{assert.throws(()=>normalizeLifecycleCatalog({vendor:'MikroTik',product:'RouterOS',sourceUrl:'http://example.com/eol'}),/HTTPS/);const row=normalizeLifecycleCatalog({vendor:'MikroTik',product:'RouterOS',productStatus:'discontinued',lastVerifiedAt:'2026-08-03',sourceUrl:'https://mikrotik.com/download'});assert.equal(row.versionPattern,'*');assert.equal(row.productStatus,'discontinued');assert.ok(row.lastVerifiedAt instanceof Date);});
test('catálogo encontra fabricante, modelo e versão por curingas',()=>{const entry={vendor:'MikroTik',modelPattern:'CCR*',versionPattern:'7.*',isActive:true};assert.equal(matchLifecycleCatalog({manufacturer:'MikroTik',model:'CCR2004',device:{osVersion:'7.19.3'}},[entry]),entry);assert.equal(matchLifecycleCatalog({manufacturer:'MikroTik',model:'CCR2004',device:{osVersion:'6.49.18'}},[entry]),null);});
test('produto oficialmente descontinuado eleva risco e recomenda substituição',()=>{const result=assessLifecycle(base,now,{productStatus:'discontinued'});assert.equal(result.riskScore,40);assert.match(result.recommendation,/descontinuado/);});
test('revisão do catálogo identifica fonte atual, vencida e nunca verificada',()=>{assert.equal(catalogVerificationStatus({},now).status,'unverified');assert.equal(catalogVerificationStatus({lastVerifiedAt:new Date('2026-07-20T12:00:00Z')},now).status,'current');assert.equal(catalogVerificationStatus({lastVerifiedAt:new Date('2026-01-01T12:00:00Z')},now).status,'stale');});
test('monitor gera alertas para produto descontinuado e fonte vencida',()=>{const asset={...base,id:'a1',name:'Core',assetTag:'AT-1',status:'active',criticality:'critical',deviceId:'d1',owner:'NOC',lastInventoryAt:now,updatedAt:now,_count:{relationshipsFrom:1,relationshipsTo:0}},catalog={product:'RB2011',productStatus:'discontinued',sourceUrl:'https://mikrotik.com/product/RB2011iL-IN',lastVerifiedAt:new Date('2026-01-01T12:00:00Z')},alerts=evaluateLifecycleAsset(asset,now,catalog);assert.equal(alerts.find(row=>row.type==='product_status')?.severity,'critical');assert.equal(alerts.find(row=>row.type==='catalog_source')?.stage,'stale');});
test('monitor usa fim de suporte oficial quando o ativo não possui contrato informado',()=>{const asset={...base,id:'a2',name:'Borda',assetTag:'AT-2',status:'active',criticality:'medium',deviceId:null,owner:'NOC',updatedAt:now,_count:{relationshipsFrom:0,relationshipsTo:0}},catalog={product:'RouterOS',productStatus:'active',sourceUrl:'https://mikrotik.com/download',lastVerifiedAt:now,endOfSupportDate:new Date('2026-08-08T12:00:00Z')},alerts=evaluateLifecycleAsset(asset,now,catalog);assert.equal(alerts.find(row=>row.type==='support')?.stage,'7d');});
