import { Router } from 'express';
import prisma from '../database/client.js';
import { cmdbInclude, cmdbSummary, listCmdbAssets, normalizeCmdbAsset } from '../services/cmdb.service.js';
import { logAudit, requestIdentity } from '../services/audit.service.js';
import { collectCmdbInventory, saveInventoryPolicy } from '../services/cmdb-inventory.service.js';
import { cmdbImpact, validateCmdbRelationship } from '../services/cmdb-relationship.service.js';
import { cmdbGovernance } from '../services/cmdb-governance.service.js';
import { approveCmdbSuggestion, ignoreCmdbSuggestion, listCmdbSuggestions, refreshCmdbSuggestions } from '../services/cmdb-discovery.service.js';
import { diffCmdbValues, listCmdbHistory, recordCmdbHistory } from '../services/cmdb-history.service.js';
import { listCmdbLifecycleAlerts, runCmdbLifecycleMonitor } from '../services/cmdb-lifecycle.service.js';
import { cidrsOverlap, listIpam, normalizeAddress, normalizeSubnet } from '../services/ipam.service.js';
import { businessServiceImpact, listBusinessServices, normalizeBusinessService, normalizeServiceAsset } from '../services/business-service.service.js';
import { decideIpamSuggestion, detectIpamConflicts, listIpamSuggestions, refreshIpamSuggestions } from '../services/ipam-reconciliation.service.js';

const router = Router();
const actor = req => String(req.user?.name || req.user?.username || 'Administrador').slice(0, 100);

router.get('/summary', async (req,res,next) => { try { res.json({ success:true, data:await cmdbSummary(req.query.tenantId || null) }); } catch(error) { next(error); } });
router.get('/governance', async (req,res,next) => { try { res.json({ success:true, data:await cmdbGovernance(req.query.tenantId || null) }); } catch(error) { next(error); } });
router.get('/suggestions',async(_req,res,next)=>{try{res.json({success:true,data:await listCmdbSuggestions()});}catch(error){next(error);}});
router.get('/lifecycle-alerts',async(req,res,next)=>{try{res.json({success:true,data:await listCmdbLifecycleAlerts(req.query.status)});}catch(error){next(error);}});
router.post('/lifecycle-alerts/scan',async(req,res,next)=>{try{const result=await runCmdbLifecycleMonitor(req.app.get('io'));await logAudit({...requestIdentity(req),action:'scan',resource:'cmdb_lifecycle',status:'success',details:result});res.json({success:true,data:result,message:`Verificação concluída: ${result.active} alerta(s) ativo(s)`});}catch(error){next(error);}});
router.get('/ipam',async(_req,res,next)=>{try{res.json({success:true,data:await listIpam()});}catch(error){next(error);}});
router.get('/ipam/conflicts',async(_req,res,next)=>{try{res.json({success:true,data:await detectIpamConflicts()});}catch(error){next(error);}});
router.post('/ipam/subnets',async(req,res,next)=>{try{const data=normalizeSubnet(req.body),scope={tenantId:data.tenantId||null,siteId:data.siteId||null},existing=await prisma.ipamSubnet.findMany({where:scope,select:{cidr:true}});if(existing.some(item=>cidrsOverlap(item.cidr,data.cidr)))return res.status(409).json({success:false,error:'A rede informada se sobrepõe a outra rede do mesmo cliente e unidade'});const row=await prisma.ipamSubnet.create({data:{...data,createdBy:actor(req)}});await logAudit({...requestIdentity(req),action:'create',resource:'ipam_subnet',resourceId:row.id,details:{cidr:row.cidr,vlanId:row.vlanId}});res.status(201).json({success:true,data:row,message:'Rede adicionada ao IPAM'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Esta rede já está cadastrada'});next(error);}});
router.delete('/ipam/subnets/:id',async(req,res,next)=>{try{const row=await prisma.ipamSubnet.findUnique({where:{id:req.params.id},include:{_count:{select:{addresses:true}}}});if(!row)return res.status(404).json({success:false,error:'Rede não encontrada'});if(row._count.addresses)return res.status(409).json({success:false,error:'Remova as reservas de IP antes de excluir a rede'});await prisma.ipamSubnet.delete({where:{id:row.id}});await logAudit({...requestIdentity(req),action:'delete',resource:'ipam_subnet',resourceId:row.id,details:{cidr:row.cidr}});res.json({success:true,message:'Rede removida'});}catch(error){next(error);}});
router.post('/ipam/addresses',async(req,res,next)=>{try{const data=await normalizeAddress(req.body),row=await prisma.ipamAddress.create({data:{...data,createdBy:actor(req)},include:{asset:true}});await logAudit({...requestIdentity(req),action:'create',resource:'ipam_address',resourceId:row.id,details:{subnetId:row.subnetId,address:row.address,assetId:row.assetId}});res.status(201).json({success:true,data:row,message:'Endereço reservado no IPAM'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Este endereço já está reservado nesta rede'});next(error);}});
router.delete('/ipam/addresses/:id',async(req,res,next)=>{try{const row=await prisma.ipamAddress.findUnique({where:{id:req.params.id}});if(!row)return res.status(404).json({success:false,error:'Endereço não encontrado'});await prisma.ipamAddress.delete({where:{id:row.id}});await logAudit({...requestIdentity(req),action:'delete',resource:'ipam_address',resourceId:row.id,details:{address:row.address}});res.json({success:true,message:'Reserva removida'});}catch(error){next(error);}});
router.get('/ipam/suggestions',async(_req,res,next)=>{try{res.json({success:true,data:await listIpamSuggestions()});}catch(error){next(error);}});
router.post('/ipam/suggestions/refresh',async(req,res,next)=>{try{const result=await refreshIpamSuggestions();await logAudit({...requestIdentity(req),action:'discover',resource:'ipam_reconciliation',details:result});res.json({success:true,data:result,message:`Reconciliação concluída: ${result.created} nova(s) sugestão(ões)`});}catch(error){next(error);}});
router.post('/ipam/suggestions/:id/approve',async(req,res,next)=>{try{const row=await decideIpamSuggestion(req.params.id,true,actor(req));await logAudit({...requestIdentity(req),action:'approve',resource:'ipam_reconciliation',resourceId:row.id});res.json({success:true,data:row,message:'Rede e endereço aprovados no IPAM'});}catch(error){next(error);}});
router.post('/ipam/suggestions/:id/ignore',async(req,res,next)=>{try{const row=await decideIpamSuggestion(req.params.id,false,actor(req));await logAudit({...requestIdentity(req),action:'ignore',resource:'ipam_reconciliation',resourceId:row.id});res.json({success:true,data:row,message:'Sugestão ignorada'});}catch(error){next(error);}});
router.get('/business-services',async(_req,res,next)=>{try{res.json({success:true,data:await listBusinessServices()});}catch(error){next(error);}});
router.post('/business-services',async(req,res,next)=>{try{const data=await normalizeBusinessService(req.body),row=await prisma.businessService.create({data:{...data,createdBy:actor(req)}});await logAudit({...requestIdentity(req),action:'create',resource:'business_service',resourceId:row.id,details:{code:row.code,tenantId:row.tenantId}});res.status(201).json({success:true,data:row,message:'Serviço de negócio cadastrado'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Este código de serviço já existe'});next(error);}});
router.put('/business-services/:id',async(req,res,next)=>{try{const current=await prisma.businessService.findUnique({where:{id:req.params.id}});if(!current)return res.status(404).json({success:false,error:'Serviço não encontrado'});const data=await normalizeBusinessService(req.body,current),row=await prisma.businessService.update({where:{id:current.id},data});await logAudit({...requestIdentity(req),action:'update',resource:'business_service',resourceId:row.id,details:{code:row.code,status:row.status}});res.json({success:true,data:row,message:'Serviço atualizado'});}catch(error){next(error);}});
router.delete('/business-services/:id',async(req,res,next)=>{try{await prisma.businessService.delete({where:{id:req.params.id}});await logAudit({...requestIdentity(req),action:'delete',resource:'business_service',resourceId:req.params.id});res.json({success:true,message:'Serviço removido'});}catch(error){if(error.code==='P2025')return res.status(404).json({success:false,error:'Serviço não encontrado'});next(error);}});
router.post('/business-services/:id/assets',async(req,res,next)=>{try{const data=await normalizeServiceAsset(req.params.id,req.body),row=await prisma.businessServiceAsset.create({data});await logAudit({...requestIdentity(req),action:'link',resource:'business_service_asset',resourceId:row.id,details:data});res.status(201).json({success:true,data:row,message:'Ativo vinculado ao serviço'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Este ativo já está vinculado ao serviço'});next(error);}});
router.delete('/business-services/:id/assets/:assetId',async(req,res,next)=>{try{await prisma.businessServiceAsset.delete({where:{serviceId_assetId:{serviceId:req.params.id,assetId:req.params.assetId}}});await logAudit({...requestIdentity(req),action:'unlink',resource:'business_service_asset',resourceId:req.params.id,details:{assetId:req.params.assetId}});res.json({success:true,message:'Ativo desvinculado'});}catch(error){if(error.code==='P2025')return res.status(404).json({success:false,error:'Vínculo não encontrado'});next(error);}});
router.get('/business-services/:id/impact',async(req,res,next)=>{try{res.json({success:true,data:await businessServiceImpact(req.params.id)});}catch(error){next(error);}});
router.post('/suggestions/refresh',async(req,res,next)=>{try{const result=await refreshCmdbSuggestions();await logAudit({...requestIdentity(req),action:'discover',resource:'cmdb_relationship_suggestion',status:'success',details:result});res.json({success:true,data:result,message:`${result.created} nova(s) sugestão(ões) encontrada(s)`});}catch(error){next(error);}});
router.post('/suggestions/:id/approve',async(req,res,next)=>{try{const row=await approveCmdbSuggestion(req.params.id,req.body,actor(req));await logAudit({...requestIdentity(req),action:'approve',resource:'cmdb_relationship_suggestion',resourceId:req.params.id,status:'success',details:{relationshipId:row.id,type:row.type}});res.json({success:true,data:row,message:'Relacionamento aprovado e adicionado ao CMDB'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Este relacionamento já existe no CMDB'});next(error);}});
router.post('/suggestions/:id/ignore',async(req,res,next)=>{try{await ignoreCmdbSuggestion(req.params.id,actor(req));await logAudit({...requestIdentity(req),action:'ignore',resource:'cmdb_relationship_suggestion',resourceId:req.params.id,status:'success'});res.json({success:true,message:'Sugestão ignorada'});}catch(error){next(error);}});
router.get('/', async (req,res,next) => { try { res.json({ success:true, data:await listCmdbAssets(req.query) }); } catch(error) { next(error); } });

router.post('/sync-devices', async (req,res,next) => {
  try {
    const devices = await prisma.device.findMany({ where: { cmdbAsset: { is: null } }, include: { tenant:true, site:true } });
    const created=[];
    for (const device of devices) {
      const data=await normalizeCmdbAsset({ name:device.name,category:'network',status:device.isActive?'active':'maintenance',criticality:'high',tenantId:device.tenantId,siteId:device.siteId,deviceId:device.id,manufacturer:device.manufacturer,model:device.model,hostname:device.hostname,tags:[device.type,device.platform,device.capabilities].filter(Boolean).join(',') },actor(req));
      const row=await prisma.cmdbAsset.create({data:{...data,createdBy:actor(req)}});created.push(row);await recordCmdbHistory({assetId:row.id,eventType:'created',source:'device_import',actor:actor(req),summary:`Ativo ${row.assetTag} importado do cadastro de equipamentos`,metadata:{deviceId:device.id}});
    }
    await logAudit({...requestIdentity(req),action:'sync',resource:'cmdb_asset',status:'success',details:{created:created.length}});
    res.json({success:true,data:{created:created.length},message:`${created.length} equipamento(s) importado(s) para a CMDB`});
  } catch(error) { next(error); }
});

router.post('/inventory/collect-all',async(req,res,next)=>{try{const assets=await prisma.cmdbAsset.findMany({where:{device:{isActive:true}},select:{id:true}}),results=[];for(const asset of assets){try{await collectCmdbInventory(asset.id,{username:actor(req)});results.push({id:asset.id,status:'success'});}catch(error){results.push({id:asset.id,status:'failed',error:error.message});}}res.json({success:true,data:{total:results.length,success:results.filter(x=>x.status==='success').length,failed:results.filter(x=>x.status==='failed').length,results},message:'Coleta geral finalizada'});}catch(error){next(error);}});
router.get('/:id/inventory',async(req,res,next)=>{try{const rows=await prisma.cmdbInventorySnapshot.findMany({where:{assetId:req.params.id},orderBy:{createdAt:'desc'},take:Math.min(Number(req.query.limit)||50,200)});res.json({success:true,data:rows.map(row=>({...row,inventoryData:row.inventoryData?JSON.parse(row.inventoryData):null}))});}catch(error){next(error);}});
router.get('/:id/interfaces',async(req,res,next)=>{try{const rows=await prisma.cmdbInterface.findMany({where:{assetId:req.params.id},orderBy:{name:'asc'}});res.json({success:true,data:rows});}catch(error){next(error);}});
router.post('/:id/interfaces',async(req,res,next)=>{try{const asset=await prisma.cmdbAsset.findUnique({where:{id:req.params.id},select:{id:true}});if(!asset)return res.status(404).json({success:false,error:'Ativo não encontrado'});const name=String(req.body.name||'').trim().slice(0,120);if(!name)return res.status(400).json({success:false,error:'Informe o nome da interface'});const vlanId=req.body.vlanId==null||req.body.vlanId===''?null:Number(req.body.vlanId);if(vlanId!==null&&(!Number.isInteger(vlanId)||vlanId<1||vlanId>4094))return res.status(400).json({success:false,error:'VLAN deve estar entre 1 e 4094'});const row=await prisma.cmdbInterface.create({data:{assetId:asset.id,name,description:String(req.body.description||'').trim().slice(0,500)||null,macAddress:String(req.body.macAddress||'').trim().slice(0,80)||null,adminStatus:String(req.body.adminStatus||'').trim().slice(0,30)||null,operStatus:String(req.body.operStatus||'').trim().slice(0,30)||null,speed:String(req.body.speed||'').trim().slice(0,40)||null,vlanId,source:String(req.body.source||'manual').trim().slice(0,30)||'manual',lastSeenAt:req.body.lastSeenAt?new Date(req.body.lastSeenAt):null}});await logAudit({...requestIdentity(req),action:'create',resource:'cmdb_interface',resourceId:row.id,details:{assetId:asset.id,name}});res.status(201).json({success:true,data:row,message:'Interface adicionada ao CMDB'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Esta interface já está cadastrada neste ativo'});next(error);}});
router.delete('/:id/interfaces/:interfaceId',async(req,res,next)=>{try{const row=await prisma.cmdbInterface.findFirst({where:{id:req.params.interfaceId,assetId:req.params.id}});if(!row)return res.status(404).json({success:false,error:'Interface não encontrada'});await prisma.cmdbInterface.delete({where:{id:row.id}});await logAudit({...requestIdentity(req),action:'delete',resource:'cmdb_interface',resourceId:row.id,details:{assetId:row.assetId,name:row.name}});res.json({success:true,message:'Interface removida'});}catch(error){next(error);}});
router.get('/:id/vlans',async(req,res,next)=>{try{const rows=await prisma.cmdbVlan.findMany({where:{assetId:req.params.id},orderBy:{vlanId:'asc'}});res.json({success:true,data:rows});}catch(error){next(error);}});
router.post('/:id/vlans',async(req,res,next)=>{try{const asset=await prisma.cmdbAsset.findUnique({where:{id:req.params.id},select:{id:true}});if(!asset)return res.status(404).json({success:false,error:'Ativo não encontrado'});const vlanId=Number(req.body.vlanId);if(!Number.isInteger(vlanId)||vlanId<1||vlanId>4094)return res.status(400).json({success:false,error:'VLAN deve estar entre 1 e 4094'});const row=await prisma.cmdbVlan.create({data:{assetId:asset.id,vlanId,name:String(req.body.name||'').trim().slice(0,120)||null,status:['active','disabled','trunk','access'].includes(req.body.status)?req.body.status:'active',source:String(req.body.source||'manual').trim().slice(0,30)||'manual',lastSeenAt:req.body.lastSeenAt?new Date(req.body.lastSeenAt):null}});await logAudit({...requestIdentity(req),action:'create',resource:'cmdb_vlan',resourceId:row.id,details:{assetId:asset.id,vlanId}});res.status(201).json({success:true,data:row,message:'VLAN adicionada ao CMDB'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Esta VLAN já está cadastrada neste ativo'});next(error);}});
router.delete('/:id/vlans/:vlanId',async(req,res,next)=>{try{const row=await prisma.cmdbVlan.findFirst({where:{id:req.params.vlanId,assetId:req.params.id}});if(!row)return res.status(404).json({success:false,error:'VLAN não encontrada'});await prisma.cmdbVlan.delete({where:{id:row.id}});await logAudit({...requestIdentity(req),action:'delete',resource:'cmdb_vlan',resourceId:row.id,details:{assetId:row.assetId,vlanId:row.vlanId}});res.json({success:true,message:'VLAN removida'});}catch(error){next(error);}});
router.get('/:id/history',async(req,res,next)=>{try{res.json({success:true,data:await listCmdbHistory(req.params.id,req.query.limit)});}catch(error){next(error);}});
router.post('/:id/inventory/collect',async(req,res,next)=>{try{const row=await collectCmdbInventory(req.params.id,{username:actor(req)});res.json({success:true,data:row,message:'Inventário coletado com sucesso'});}catch(error){next(error);}});
router.put('/:id/inventory/policy',async(req,res,next)=>{try{const row=await saveInventoryPolicy(req.params.id,req.body);await logAudit({...requestIdentity(req),action:'update',resource:'cmdb_inventory_policy',resourceId:row.id,details:{assetId:req.params.id,enabled:row.enabled,frequency:row.frequency,nextRunAt:row.nextRunAt}});res.json({success:true,data:row,message:'Agenda de inventário atualizada'});}catch(error){next(error);}});
router.get('/:id/impact',async(req,res,next)=>{try{res.json({success:true,data:await cmdbImpact(req.params.id)});}catch(error){next(error);}});
router.post('/relationships',async(req,res,next)=>{try{const validated=await validateCmdbRelationship(req.body);const row=await prisma.cmdbRelationship.create({data:{...validated.data,createdBy:actor(req)},include:{sourceAsset:true,targetAsset:true}});for(const assetId of [row.sourceAssetId,row.targetAssetId])await recordCmdbHistory({assetId,eventType:'relationship_created',source:'manual',actor:actor(req),summary:`Relacionamento ${row.type} criado entre ${row.sourceAsset.name} e ${row.targetAsset.name}`,metadata:{relationshipId:row.id,type:row.type,critical:row.critical}});await logAudit({...requestIdentity(req),action:'create',resource:'cmdb_relationship',resourceId:row.id,details:{sourceAssetId:row.sourceAssetId,targetAssetId:row.targetAssetId,type:row.type,critical:row.critical}});res.status(201).json({success:true,data:row,message:'Relacionamento criado'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Este relacionamento já existe'});next(error);}});
router.delete('/relationships/:id',async(req,res,next)=>{try{const row=await prisma.cmdbRelationship.findUnique({where:{id:req.params.id},include:{sourceAsset:{select:{name:true}},targetAsset:{select:{name:true}}}});if(!row)return res.status(404).json({success:false,error:'Relacionamento não encontrado'});await prisma.cmdbRelationship.delete({where:{id:row.id}});for(const assetId of [row.sourceAssetId,row.targetAssetId])await recordCmdbHistory({assetId,eventType:'relationship_deleted',source:'manual',actor:actor(req),summary:`Relacionamento ${row.type} removido entre ${row.sourceAsset.name} e ${row.targetAsset.name}`,metadata:{relationshipId:row.id,type:row.type}});await logAudit({...requestIdentity(req),action:'delete',resource:'cmdb_relationship',resourceId:row.id,details:{sourceAssetId:row.sourceAssetId,targetAssetId:row.targetAssetId,type:row.type}});res.json({success:true,message:'Relacionamento removido'});}catch(error){next(error);}});

router.get('/:id',async(req,res,next)=>{try{const row=await prisma.cmdbAsset.findUnique({where:{id:req.params.id},include:cmdbInclude});if(!row)return res.status(404).json({success:false,error:'Ativo não encontrado'});res.json({success:true,data:row});}catch(error){next(error);}});
router.post('/',async(req,res,next)=>{try{const data=await normalizeCmdbAsset(req.body,actor(req));const row=await prisma.cmdbAsset.create({data:{...data,createdBy:actor(req)},include:cmdbInclude});await recordCmdbHistory({assetId:row.id,eventType:'created',source:'manual',actor:actor(req),summary:`Ativo ${row.assetTag} cadastrado no CMDB`});await logAudit({...requestIdentity(req),action:'create',resource:'cmdb_asset',resourceId:row.id,details:{assetTag:row.assetTag,name:row.name,tenantId:row.tenantId}});res.status(201).json({success:true,data:row,message:'Ativo cadastrado na CMDB'});}catch(error){next(error);}});
router.put('/:id',async(req,res,next)=>{try{const current=await prisma.cmdbAsset.findUnique({where:{id:req.params.id}});if(!current)return res.status(404).json({success:false,error:'Ativo não encontrado'});const data=await normalizeCmdbAsset(req.body,actor(req),current),changes=diffCmdbValues(current,data);const row=await prisma.cmdbAsset.update({where:{id:current.id},data,include:cmdbInclude});await recordCmdbHistory({assetId:row.id,eventType:'updated',source:'manual',actor:actor(req),summary:changes.length?`${changes.length} campo(s) alterado(s) no cadastro`:'Cadastro salvo sem diferenças',changes});await logAudit({...requestIdentity(req),action:'update',resource:'cmdb_asset',resourceId:row.id,details:{assetTag:row.assetTag,name:row.name,status:row.status}});res.json({success:true,data:row,message:'Ativo atualizado'});}catch(error){next(error);}});
router.delete('/:id',async(req,res,next)=>{try{const row=await prisma.cmdbAsset.findUnique({where:{id:req.params.id},select:{id:true,assetTag:true,name:true}});if(!row)return res.status(404).json({success:false,error:'Ativo não encontrado'});await prisma.cmdbAsset.delete({where:{id:row.id}});await logAudit({...requestIdentity(req),action:'delete',resource:'cmdb_asset',resourceId:row.id,details:{assetTag:row.assetTag,name:row.name}});res.json({success:true,message:'Ativo removido da CMDB'});}catch(error){next(error);}});

export default router;
