import {Router} from 'express';
import {lifecycleDashboard} from '../services/lifecycle.service.js';
import {runCmdbLifecycleMonitor} from '../services/cmdb-lifecycle.service.js';
import {logAudit,requestIdentity} from '../services/audit.service.js';
import prisma from '../database/client.js';
import {createTask} from '../services/task.service.js';
import {listLifecycleCatalog,normalizeLifecycleCatalog} from '../services/lifecycle-catalog.service.js';

const router=Router();
router.get('/',async(req,res,next)=>{try{res.json({success:true,data:await lifecycleDashboard(req.query)});}catch(error){next(error);}});
router.post('/scan',async(req,res,next)=>{try{const result=await runCmdbLifecycleMonitor(req.app.get('io'));await logAudit({...requestIdentity(req),action:'scan',resource:'lifecycle',status:'success',details:result});res.json({success:true,data:result,message:`Ciclo de vida atualizado: ${result.active} alerta(s) ativo(s)`});}catch(error){next(error);}});
router.get('/catalog',async(req,res,next)=>{try{res.json({success:true,data:await listLifecycleCatalog(req.query)});}catch(error){next(error);}});
router.post('/catalog',async(req,res,next)=>{try{const data=normalizeLifecycleCatalog(req.body),actor=String(req.user.name||req.user.username),row=await prisma.lifecycleCatalogEntry.create({data:{...data,createdBy:actor,updatedBy:actor}});await logAudit({...requestIdentity(req),action:'create',resource:'lifecycle_catalog',resourceId:row.id,status:'success',details:{vendor:row.vendor,product:row.product,versionPattern:row.versionPattern}});res.status(201).json({success:true,data:row,message:'Entrada adicionada ao catálogo'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Esta combinação de produto, modelo e versão já existe'});next(error);}});
router.put('/catalog/:id',async(req,res,next)=>{try{const current=await prisma.lifecycleCatalogEntry.findUnique({where:{id:req.params.id}});if(!current)return res.status(404).json({success:false,error:'Entrada não encontrada'});const data=normalizeLifecycleCatalog({...current,...req.body}),actor=String(req.user.name||req.user.username),row=await prisma.lifecycleCatalogEntry.update({where:{id:current.id},data:{...data,updatedBy:actor}});await logAudit({...requestIdentity(req),action:'update',resource:'lifecycle_catalog',resourceId:row.id,status:'success',details:{before:{productStatus:current.productStatus,endOfSaleDate:current.endOfSaleDate,endOfSupportDate:current.endOfSupportDate,sourceUrl:current.sourceUrl},after:{productStatus:row.productStatus,endOfSaleDate:row.endOfSaleDate,endOfSupportDate:row.endOfSupportDate,sourceUrl:row.sourceUrl}}});res.json({success:true,data:row,message:'Catálogo atualizado'});}catch(error){if(error.code==='P2002')return res.status(409).json({success:false,error:'Esta combinação de produto, modelo e versão já existe'});next(error);}});
router.post('/catalog/:id/verify',async(req,res,next)=>{try{const row=await prisma.lifecycleCatalogEntry.update({where:{id:req.params.id},data:{lastVerifiedAt:new Date(),updatedBy:String(req.user.name||req.user.username)}});await logAudit({...requestIdentity(req),action:'verify',resource:'lifecycle_catalog',resourceId:row.id,status:'success',details:{sourceUrl:row.sourceUrl,productStatus:row.productStatus}});res.json({success:true,data:row,message:'Revisão da fonte confirmada'});}catch(error){if(error.code==='P2025')return res.status(404).json({success:false,error:'Entrada não encontrada'});next(error);}});
router.delete('/catalog/:id',async(req,res,next)=>{try{const row=await prisma.lifecycleCatalogEntry.update({where:{id:req.params.id},data:{isActive:false,updatedBy:String(req.user.name||req.user.username)}});await logAudit({...requestIdentity(req),action:'deactivate',resource:'lifecycle_catalog',resourceId:row.id,status:'success'});res.json({success:true,message:'Entrada desativada'});}catch(error){if(error.code==='P2025')return res.status(404).json({success:false,error:'Entrada não encontrada'});next(error);}});
router.post('/:assetId/task',async(req,res,next)=>{try{const asset=await prisma.cmdbAsset.findUnique({where:{id:req.params.assetId},include:{device:{select:{id:true,name:true,hostname:true,osVersion:true}},tenant:{select:{name:true}},lifecycleAlerts:{where:{status:'active'},select:{title:true,message:true,severity:true}}}});if(!asset)return res.status(404).json({success:false,error:'Ativo não encontrado'});if(!asset.deviceId)return res.status(400).json({success:false,error:'Vincule o ativo a um equipamento antes de criar a Task'});const incidentKey=`lifecycle:${asset.id}`,current=await prisma.task.findFirst({where:{incidentKey,status:{notIn:['resolved','completed','validated','closed','cancelled']}},orderBy:{createdAt:'desc'}});if(current)return res.json({success:true,data:current,message:`Task #${current.taskNumber} já acompanha este ativo`});const reason=String(req.body.reason||'Revisar renovação, atualização ou substituição do ativo').trim().slice(0,1000),evidence=asset.lifecycleAlerts.map(row=>`- ${row.title}: ${row.message}`).join('\n')||'- Cadastro de ciclo de vida requer revisão.';const task=await createTask({source:'lifecycle',workType:'maintenance',deviceId:asset.deviceId,priority:asset.criticality==='critical'?'critical':asset.criticality==='high'?'high':'medium',originalMessage:`Ciclo de vida do ativo ${asset.assetTag} — ${asset.name}\nCliente: ${asset.tenant?.name||'Global'}\nEquipamento: ${asset.device.name} (${asset.device.hostname})\nVersão: ${asset.device.osVersion||'não coletada'}\nObjetivo: ${reason}\nEvidências:\n${evidence}`,incident:{incidentKey,incidentOpenedAt:new Date()}});await logAudit({...requestIdentity(req),action:'create_task',resource:'lifecycle',resourceId:asset.id,status:'success',details:{taskNumber:task.taskNumber,deviceId:asset.deviceId}});res.status(201).json({success:true,data:task,message:`Task #${task.taskNumber} criada para o ciclo de vida`});}catch(error){next(error);}});
export default router;
