import {Router} from'express';
import prisma from'../database/client.js';
import {getPublicStatusPage,INCIDENT_STATES,SERVICE_STATES,syncStatusServices} from'../services/status-page.service.js';
import {logAudit,requestIdentity} from'../services/audit.service.js';
import {notifyStatusPageEvent} from'../services/notification.service.js';

export const publicStatusRouter=Router(),statusAdminRouter=Router();
const actor=req=>req.user?.name||req.user?.username||'Sistema';
const bad=message=>Object.assign(new Error(message),{statusCode:400});
const audit=(req,action,id,details)=>logAudit({...requestIdentity(req),action,resource:'status_page',resourceId:id,details});
publicStatusRouter.get('/',async(_req,res,next)=>{try{res.json({success:true,data:await getPublicStatusPage()});}catch(error){next(error);}});

statusAdminRouter.get('/',async(_req,res,next)=>{try{
  await syncStatusServices();const[services,tasks,settings]=await Promise.all([prisma.statusService.findMany({orderBy:[{sortOrder:'asc'},{name:'asc'}],include:{device:{select:{id:true,name:true}},incidents:{orderBy:{publishedAt:'desc'},include:{updates:{orderBy:{createdAt:'desc'}}}}}}),prisma.task.findMany({where:{workType:'incident'},orderBy:{createdAt:'desc'},take:100,select:{id:true,taskNumber:true,originalMessage:true,priority:true,status:true,deviceId:true}}),prisma.settings.findMany({where:{key:{in:['status_page_title','status_page_description']}}})]);res.json({success:true,data:{services,tasks,config:Object.fromEntries(settings.map(item=>[item.key,item.value]))}});
}catch(error){next(error);}});
statusAdminRouter.put('/config',async(req,res,next)=>{try{for(const[key,value]of Object.entries({status_page_title:String(req.body.title||'').slice(0,100),status_page_description:String(req.body.description||'').slice(0,300)}))await prisma.settings.upsert({where:{key},update:{value},create:{key,value}});res.json({success:true,message:'Status Page atualizada'});}catch(error){next(error);}});
statusAdminRouter.post('/services',async(req,res,next)=>{try{const name=String(req.body.name||'').trim();if(name.length<3)throw bad('Informe o nome do serviço');const row=await prisma.statusService.create({data:{name:name.slice(0,100),description:String(req.body.description||'').trim().slice(0,300)||null,deviceId:req.body.deviceId||null,automatic:req.body.automatic!==false,manualStatus:SERVICE_STATES.includes(req.body.manualStatus)?req.body.manualStatus:'operational',sortOrder:Number(req.body.sortOrder)||100},});await prisma.statusServiceEvent.create({data:{serviceId:row.id,status:row.currentStatus}});await audit(req,'service_create',row.id,{name});res.status(201).json({success:true,data:row,message:'Serviço criado'});}catch(error){next(error);}});
statusAdminRouter.put('/services/:id',async(req,res,next)=>{try{const data={};for(const key of['name','description'])if(req.body[key]!==undefined)data[key]=String(req.body[key]).trim().slice(0,key==='name'?100:300)||null;if(req.body.deviceId!==undefined)data.deviceId=req.body.deviceId||null;if(typeof req.body.enabled==='boolean')data.enabled=req.body.enabled;if(typeof req.body.automatic==='boolean')data.automatic=req.body.automatic;if(SERVICE_STATES.includes(req.body.manualStatus))data.manualStatus=req.body.manualStatus;if(req.body.sortOrder!==undefined)data.sortOrder=Number(req.body.sortOrder)||100;const row=await prisma.statusService.update({where:{id:req.params.id},data});await syncStatusServices();res.json({success:true,data:row,message:'Serviço atualizado'});}catch(error){next(error);}});
statusAdminRouter.delete('/services/:id',async(req,res,next)=>{try{await prisma.statusService.delete({where:{id:req.params.id}});res.json({success:true,message:'Serviço excluído'});}catch(error){next(error);}});

statusAdminRouter.post('/incidents',async(req,res,next)=>{try{const service=await prisma.statusService.findUnique({where:{id:String(req.body.serviceId)}});if(!service)throw bad('Serviço inválido');const title=String(req.body.title||'').trim(),message=String(req.body.message||'').trim();if(title.length<3||message.length<5)throw bad('Informe título e mensagem pública');const scheduled=req.body.status==='scheduled';const scheduledAt=scheduled?new Date(req.body.scheduledAt):null,scheduledEndAt=scheduled?new Date(req.body.scheduledEndAt):null;if(scheduled&&(!Number.isFinite(scheduledAt.getTime())||!Number.isFinite(scheduledEndAt.getTime())||scheduledEndAt<=scheduledAt))throw bad('Janela de manutenção inválida');const severity=SERVICE_STATES.includes(req.body.severity)&&req.body.severity!=='operational'?req.body.severity:'degraded';const row=await prisma.statusIncident.create({data:{serviceId:service.id,taskId:req.body.taskId||null,title:title.slice(0,140),message:message.slice(0,2000),severity,status:scheduled?'scheduled':'investigating',scheduledAt,scheduledEndAt,createdBy:actor(req)}});await prisma.statusIncidentUpdate.create({data:{incidentId:row.id,status:row.status,message:row.message,createdBy:actor(req)}});await syncStatusServices();await notifyStatusPageEvent({resourceId:row.id,event:'status_incident_published',title:row.title,message:row.message,critical:severity==='major_outage'});await audit(req,'incident_publish',row.id,{service:service.name,taskId:row.taskId});res.status(201).json({success:true,data:row,message:'Incidente publicado'});}catch(error){next(error);}});
statusAdminRouter.post('/incidents/:id/updates',async(req,res,next)=>{try{const status=String(req.body.status),message=String(req.body.message||'').trim();if(!INCIDENT_STATES.includes(status)||message.length<5)throw bad('Atualização inválida');const incident=await prisma.statusIncident.update({where:{id:req.params.id},data:{status,resolvedAt:status==='resolved'?new Date():null}});const row=await prisma.statusIncidentUpdate.create({data:{incidentId:incident.id,status,message:message.slice(0,2000),createdBy:actor(req)}});await syncStatusServices();await notifyStatusPageEvent({resourceId:incident.id,event:`status_incident_${status}_${row.id}`,title:incident.title,message,critical:incident.severity==='major_outage'&&status!=='resolved'});await audit(req,'incident_update',incident.id,{status});res.json({success:true,data:row,message:'Atualização publicada'});}catch(error){next(error);}});

export default statusAdminRouter;
