import {Router} from 'express';
import prisma from '../database/client.js';
import {logAudit,requestIdentity} from '../services/audit.service.js';

const router=Router(),bad=message=>Object.assign(new Error(message),{statusCode:400}),text=(value,max=255)=>String(value||'').trim().slice(0,max)||null;
export function normalizeSupplier(input){const name=text(input.name,140),status=['active','inactive','blocked'].includes(input.status)?input.status:'active',rating=input.rating===null||input.rating===''||input.rating===undefined?null:Number(input.rating);if(!name)throw bad('Informe o nome do fornecedor');if(rating!==null&&(!Number.isInteger(rating)||rating<1||rating>5))throw bad('A avaliação deve ser de 1 a 5');const website=text(input.website,500);if(website&&!/^https:\/\//i.test(website))throw bad('O site deve usar HTTPS');return{name,tenantId:text(input.tenantId,80),legalName:text(input.legalName,180),document:text(input.document,40),status,manufacturers:text(input.manufacturers,500),website,supportHours:text(input.supportHours,160),technicalName:text(input.technicalName),technicalEmail:text(input.technicalEmail),technicalPhone:text(input.technicalPhone,40),commercialName:text(input.commercialName),commercialEmail:text(input.commercialEmail),commercialPhone:text(input.commercialPhone,40),escalationPhone:text(input.escalationPhone,40),rating,notes:text(input.notes,2000)};}
router.get('/',async(req,res,next)=>{try{const where={...(req.query.status&&req.query.status!=='all'&&{status:String(req.query.status)}),...(req.query.tenantId&&{tenantId:String(req.query.tenantId)})},rows=await prisma.supplier.findMany({where,include:{tenant:{select:{id:true,name:true}}},orderBy:[{status:'asc'},{name:'asc'}],take:1000});res.json({success:true,data:rows});}catch(error){next(error);}});
router.post('/',async(req,res,next)=>{try{const actor=String(req.user.name||req.user.username),data=normalizeSupplier(req.body);if(data.tenantId&&!await prisma.tenant.findUnique({where:{id:data.tenantId},select:{id:true}}))throw bad('Cliente não encontrado');const row=await prisma.supplier.create({data:{...data,createdBy:actor,updatedBy:actor}});await logAudit({...requestIdentity(req),action:'create',resource:'supplier',resourceId:row.id,status:'success',details:{name:row.name,tenantId:row.tenantId}});res.status(201).json({success:true,data:row,message:'Fornecedor cadastrado'});}catch(error){next(error);}});
router.put('/:id',async(req,res,next)=>{try{const current=await prisma.supplier.findUnique({where:{id:req.params.id}});if(!current)return res.status(404).json({success:false,error:'Fornecedor não encontrado'});const data=normalizeSupplier({...current,...req.body}),row=await prisma.supplier.update({where:{id:current.id},data:{...data,updatedBy:String(req.user.name||req.user.username)}});await logAudit({...requestIdentity(req),action:'update',resource:'supplier',resourceId:row.id,status:'success',details:{before:{status:current.status,rating:current.rating},after:{status:row.status,rating:row.rating}}});res.json({success:true,data:row,message:'Fornecedor atualizado'});}catch(error){next(error);}});
router.delete('/:id',async(req,res,next)=>{try{const row=await prisma.supplier.update({where:{id:req.params.id},data:{status:'inactive',updatedBy:String(req.user.name||req.user.username)}});await logAudit({...requestIdentity(req),action:'deactivate',resource:'supplier',resourceId:row.id,status:'success'});res.json({success:true,message:'Fornecedor desativado'});}catch(error){if(error.code==='P2025')return res.status(404).json({success:false,error:'Fornecedor não encontrado'});next(error);}});
export default router;
