import{Router}from'express';import prisma from'../database/client.js';import{logAudit,requestIdentity}from'../services/audit.service.js';
const router=Router(),bad=message=>Object.assign(new Error(message),{statusCode:400});
const slug=value=>String(value||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
router.get('/',async(_req,res,next)=>{try{res.json({success:true,data:await prisma.tenant.findMany({orderBy:{name:'asc'},include:{sites:true,_count:{select:{users:true,devices:true,tasks:true}}}})});}catch(e){next(e);}});
router.post('/',async(req,res,next)=>{try{const name=String(req.body.name||'').trim(),key=slug(req.body.slug||name);if(name.length<3||key.length<2)throw bad('Informe nome e identificador válidos');const row=await prisma.tenant.create({data:{name:name.slice(0,120),slug:key,document:String(req.body.document||'').trim()||null,contactName:String(req.body.contactName||'').trim()||null,contactEmail:String(req.body.contactEmail||'').trim()||null,contactPhone:String(req.body.contactPhone||'').replace(/\D/g,'')||null}});await logAudit({...requestIdentity(req),action:'create',resource:'tenant',resourceId:row.id,details:{name,key}});res.status(201).json({success:true,data:row,message:'Cliente criado'});}catch(e){next(e);}});
router.put('/:id',async(req,res,next)=>{try{const data={};for(const key of['name','document','contactName','contactEmail','contactPhone','portalTitle','portalDescription'])if(req.body[key]!==undefined)data[key]=String(req.body[key]).trim()||null;if(req.body.primaryColor!==undefined){if(!/^#[0-9a-f]{6}$/i.test(req.body.primaryColor))throw bad('Cor inválida');data.primaryColor=req.body.primaryColor;}for(const key of['slaLowAck','slaLowResolve','slaMediumAck','slaMediumResolve','slaHighAck','slaHighResolve','slaCriticalAck','slaCriticalResolve'])if(req.body[key]!==undefined)data[key]=req.body[key]?Math.max(1,Number(req.body[key])):null;if(typeof req.body.isActive==='boolean')data.isActive=req.body.isActive;const row=await prisma.tenant.update({where:{id:req.params.id},data});res.json({success:true,data:row,message:'Cliente atualizado'});}catch(e){next(e);}});
router.post('/:id/sites',async(req,res,next)=>{try{const name=String(req.body.name||'').trim();if(name.length<2)throw bad('Informe o nome da unidade');const row=await prisma.tenantSite.create({data:{tenantId:req.params.id,name:name.slice(0,100),city:String(req.body.city||'').trim()||null,state:String(req.body.state||'').trim().slice(0,2).toUpperCase()||null}});res.status(201).json({success:true,data:row,message:'Unidade criada'});}catch(e){next(e);}});
router.delete('/sites/:id',async(req,res,next)=>{try{await prisma.tenantSite.delete({where:{id:req.params.id}});res.json({success:true,message:'Unidade excluída'});}catch(e){next(e);}});
export default router;
