import prisma from '../database/client.js';
import { calculateImpact } from './cmdb-relationship.service.js';

const bad=(message,statusCode=400)=>Object.assign(new Error(message),{statusCode});
const text=(value,max=255)=>String(value||'').trim().slice(0,max)||null;
const CRITICALITIES=['low','medium','high','critical'],STATUSES=['active','maintenance','inactive'],ROLES=['primary','dependency','backup'];

export async function normalizeBusinessService(input,current=null){const merged={...(current||{}),...input},name=text(merged.name,140),code=text(merged.code,50)?.toUpperCase().replace(/[^A-Z0-9_-]/g,'-');if(!name||name.length<3)throw bad('Informe o nome do serviço');if(!code||code.length<2)throw bad('Informe um código válido');const tenantId=text(merged.tenantId,50);if(tenantId&&!await prisma.tenant.findFirst({where:{id:tenantId,isActive:true},select:{id:true}}))throw bad('Cliente inválido');const sla=merged.slaMinutes===''||merged.slaMinutes==null?null:Number(merged.slaMinutes);if(sla!==null&&(!Number.isInteger(sla)||sla<1||sla>525600))throw bad('SLA deve ser informado em minutos');return{name,code,description:text(merged.description,1500),tenantId,criticality:CRITICALITIES.includes(merged.criticality)?merged.criticality:'medium',status:STATUSES.includes(merged.status)?merged.status:'active',owner:text(merged.owner,120),contact:text(merged.contact,180),slaMinutes:sla};}
export async function listBusinessServices(){return prisma.businessService.findMany({include:{tenant:{select:{id:true,name:true}},assets:{include:{asset:{select:{id:true,assetTag:true,name:true,status:true,criticality:true,tenantId:true}}},orderBy:[{critical:'desc'},{createdAt:'asc'}]}},orderBy:[{status:'asc'},{name:'asc'}]});}
export async function normalizeServiceAsset(serviceId,input){const service=await prisma.businessService.findUnique({where:{id:serviceId}}),asset=await prisma.cmdbAsset.findUnique({where:{id:String(input.assetId||'')}});if(!service)throw bad('Serviço não encontrado',404);if(!asset)throw bad('Ativo não encontrado');if(service.tenantId&&asset.tenantId&&service.tenantId!==asset.tenantId)throw bad('O ativo pertence a outro cliente');return{serviceId,assetId:asset.id,role:ROLES.includes(input.role)?input.role:'dependency',critical:input.critical===true};}
export async function businessServiceImpact(id){const service=await prisma.businessService.findUnique({where:{id},include:{tenant:{select:{id:true,name:true}},assets:{include:{asset:true}}}});if(!service)throw bad('Serviço não encontrado',404);const[assets,relationships]=await Promise.all([prisma.cmdbAsset.findMany({select:{id:true,assetTag:true,name:true,category:true,status:true,criticality:true,tenantId:true,manufacturer:true,model:true}}),prisma.cmdbRelationship.findMany()]),seen=new Map();for(const link of service.assets){seen.set(link.assetId,{asset:link.asset,depth:0,source:'service',critical:link.critical});for(const item of calculateImpact(link.assetId,assets,relationships))if(!seen.has(item.asset.id))seen.set(item.asset.id,{...item,source:'dependency',critical:item.relationship.critical});}const impacted=[...seen.values()];return{service,impacted,summary:{assets:service.assets.length,total:impacted.length,unavailable:impacted.filter(row=>row.asset.status!=='active').length,critical:impacted.filter(row=>row.critical||row.asset.criticality==='critical').length}};}
