import {createRequire} from 'node:module';
import PDFDocument from 'pdfkit';
const require=createRequire(import.meta.url),pdfParse=require('pdf-parse');
const allowed=new Set(['txt','log','conf','cfg','md','json','xml','yaml','yml','csv','rsc','pdf']);
const secret=/\b(password|passwd|senha|secret|community|token|api[_ -]?key|private-key|pre-shared-key|preshared-key)\s*[=: ]\s*\S+/gi;
export const maskChatSecrets=value=>String(value||'').replace(secret,'$1=[PROTEGIDO]');
export async function extractChatAttachment({filename,data}){const name=String(filename||'arquivo').replace(/[\r\n"\\/]/g,'_').slice(0,160),ext=name.split('.').pop()?.toLowerCase();if(!allowed.has(ext))throw Object.assign(new Error('Formato não permitido. Use TXT, LOG, CONF, CFG, MD, JSON, XML, YAML, CSV, RSC ou PDF.'),{statusCode:400});const buffer=Buffer.from(String(data||''),'base64'),limit=ext==='pdf'?5*1024*1024:2*1024*1024;if(!buffer.length||buffer.length>limit)throw Object.assign(new Error(`Arquivo inválido ou maior que ${ext==='pdf'?'5 MB':'2 MB'}`),{statusCode:400});let text;if(ext==='pdf'){try{text=(await pdfParse(buffer)).text}catch{throw Object.assign(new Error('Não foi possível extrair o texto do PDF'),{statusCode:400})}}else text=buffer.toString('utf8');text=String(text||'').replace(/\0/g,'').trim();if(!text)throw Object.assign(new Error('O arquivo não contém texto legível'),{statusCode:400});return{filename:name,mimeType:ext==='pdf'?'application/pdf':'text/plain',size:buffer.length,content:text.slice(0,250000)}}
export function chatMarkdown(session,messages){const lines=[`# ${session.title||'Conversa do Chat AI'}`,'',`Exportado em: ${new Date().toLocaleString('pt-BR')}`,''];for(const row of messages){lines.push(`## ${row.role==='assistant'?'Agente':'Usuário'} · ${new Date(row.createdAt).toLocaleString('pt-BR')}`);if(row.agentUsed)lines.push(`Agente: ${row.agentUsed}${row.provider?` · ${row.provider}`:''}${row.model?` · ${row.model}`:''}`);if(row.attachments?.length)lines.push(`Anexos: ${row.attachments.map(x=>x.filename).join(', ')}`);lines.push('',row.content,'')}return lines.join('\n')}
export async function chatPdf(session,messages){const doc=new PDFDocument({size:'A4',margin:44,bufferPages:true,info:{Title:session.title||'Chat AI'}}),chunks=[];doc.on('data',x=>chunks.push(x));doc.fontSize(18).fillColor('#123047').text(session.title||'Conversa do Chat AI');doc.fontSize(8).fillColor('#526577').text(`Exportado em ${new Date().toLocaleString('pt-BR')}`);doc.moveDown();for(const row of messages){if(doc.y>710)doc.addPage();doc.fontSize(10).fillColor(row.role==='assistant'?'#075985':'#334155').text(`${row.role==='assistant'?'Agente':'Usuário'} · ${new Date(row.createdAt).toLocaleString('pt-BR')}`);if(row.agentUsed)doc.fontSize(7).fillColor('#64748b').text(`${row.agentUsed}${row.provider?` · ${row.provider}`:''}${row.model?` · ${row.model}`:''}`);if(row.attachments?.length)doc.fontSize(7).text(`Anexos: ${row.attachments.map(x=>x.filename).join(', ')}`);doc.fontSize(8).fillColor('#1e293b').text(String(row.content||''),{lineGap:2});doc.moveDown()}doc.end();await new Promise((resolve,reject)=>{doc.on('end',resolve);doc.on('error',reject)});return Buffer.concat(chunks)}
