import net from 'node:net';
import prisma from '../database/client.js';
import { executeManagedDeviceCommand } from './cli.service.js';
import { runDeviceBackup } from './device-backup.service.js';
import { addTaskMessage } from './task.service.js';

const reservedDns=new Set(['8.8.8.8','8.8.4.4','1.1.1.1','1.0.0.1','9.9.9.9','149.112.112.112']);
const canonical=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]/g,'').split('').sort().join('');
export function publicMitigationTarget(ip){if(net.isIP(ip)!==4)return false;const parts=ip.split('.').map(Number),[a,b]=parts;return !(a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===198&&[18,19].includes(b))||reservedDns.has(ip));}
const quote=value=>String(value).replaceAll('\\','\\\\').replaceAll('"','\\"');

export async function prepareFlowMitigation(anomalyId,{durationMinutes=30,username}){const anomaly=await prisma.flowAnomaly.findUnique({where:{id:anomalyId}});if(!anomaly||anomaly.status!=='confirmed'||anomaly.classification!=='attack')throw Object.assign(new Error('A mitigação exige uma anomalia confirmada como ataque'),{statusCode:409});const targetIp=String(anomaly.sourceAddress||'');if(!publicMitigationTarget(targetIp))throw Object.assign(new Error('Mitigação recusada: somente IP público externo pode ser bloqueado'),{statusCode:400});const [protectedAddress,protectedDevice]=await Promise.all([prisma.ipamAddress.findFirst({where:{address:targetIp,status:{not:'available'}}}),prisma.device.findFirst({where:{hostname:targetIp,isActive:true}})]);if(protectedAddress||protectedDevice)throw Object.assign(new Error('Mitigação recusada: endereço protegido por Equipamentos/IPAM/CMDB'),{statusCode:400});const devices=await prisma.device.findMany({where:{isActive:true,type:'mikrotik'}}),device=devices.find(row=>canonical(row.name)===canonical(anomaly.exporterName)||canonical(row.hostname)===canonical(anomaly.exporterName));if(!device)throw Object.assign(new Error(`Não foi possível relacionar ${anomaly.exporterName} a um MikroTik cadastrado`),{statusCode:400});const minutes=Math.min(240,Math.max(5,Math.round(Number(durationMinutes)||30))),list='NOC-ASSISTED-BLOCK',comment=`NOC Agent: mitigação assistida; Task #${anomaly.taskId||'sem-task'}; ${minutes}min`,command=`/ip firewall address-list add list=${list} address=${targetIp} timeout=${minutes}m comment="${quote(comment)}"`,validationCommand=`/ip firewall address-list print detail where list=${list} and address=${targetIp}`,rollbackCommand=`/ip firewall address-list remove [find where list=${list} and address=${targetIp}]`;const existing=await prisma.flowMitigation.findFirst({where:{anomalyId,status:{in:['proposed','active']}}});if(existing)return existing;return prisma.flowMitigation.create({data:{anomalyId,taskId:anomaly.taskId,deviceId:device.id,deviceName:device.name,targetIp,addressList:list,durationMinutes:minutes,command,validationCommand,rollbackCommand,requestedBy:username}})}

export async function approveFlowMitigation(id,{username,confirmed}){if(confirmed!==true)throw Object.assign(new Error('Confirmação explícita obrigatória'),{statusCode:400});const row=await prisma.flowMitigation.findUnique({where:{id}});if(!row||row.status!=='proposed')throw Object.assign(new Error('Mitigação não está disponível para execução'),{statusCode:409});const device=await prisma.device.findUnique({where:{id:row.deviceId}});if(!device||device.type!=='mikrotik')throw Object.assign(new Error('Equipamento MikroTik indisponível'),{statusCode:400});const prerequisite=await executeManagedDeviceCommand({device,command:`/ip firewall filter print count-only where src-address-list=${row.addressList} and action=drop`,approved:false});if(!prerequisite.success||Number(String(prerequisite.output||'').match(/\d+/)?.[0]||0)<1)throw Object.assign(new Error(`Execução bloqueada: não existe regra drop controlada para a lista ${row.addressList}`),{statusCode:409});await runDeviceBackup(device.id,{type:'pre_mitigation',username});const result=await executeManagedDeviceCommand({device,command:row.command,changeComment:`Mitigação assistida do IP ${row.targetIp}`,approved:true,agentName:'flow-mitigation'});if(!result.success){await prisma.flowMitigation.update({where:{id},data:{status:'failed',approvedBy:username,approvedAt:new Date(),result:String(result.output||'').slice(0,4000)}});throw new Error(result.output||'Falha na mitigação')}const validation=await executeManagedDeviceCommand({device,command:row.validationCommand,approved:false}),now=new Date(),updated=await prisma.flowMitigation.update({where:{id},data:{status:'active',approvedBy:username,approvedAt:now,executedAt:now,expiresAt:new Date(now.getTime()+row.durationMinutes*60000),result:String(validation.output||result.output||'').slice(0,4000)}});if(row.taskId)await addTaskMessage(row.taskId,'system',`Mitigação temporária aprovada por ${username}: IP ${row.targetIp} na lista ${row.addressList} por ${row.durationMinutes} minutos.`);return updated;}

export async function listFlowMitigations(){const now=new Date();await prisma.flowMitigation.updateMany({where:{status:'active',expiresAt:{lte:now}},data:{status:'expired'}});return prisma.flowMitigation.findMany({orderBy:{createdAt:'desc'},take:100});}
