import prisma from '../database/client.js';

const fail=(message,statusCode=400)=>Object.assign(new Error(message),{statusCode});
export const ipv4ToInt=value=>{const parts=String(value||'').trim().split('.');if(parts.length!==4||parts.some(part=>!/^\d{1,3}$/.test(part)||Number(part)>255))throw fail('Endereço IPv4 inválido');return parts.reduce((total,part)=>(total*256+Number(part))>>>0,0)>>>0;};
export const intToIpv4=value=>[24,16,8,0].map(shift=>(value>>>shift)&255).join('.');
export function parseCidr(value){const raw=String(value||'').trim(),[ip,prefixRaw,...extra]=raw.split('/'),prefix=Number(prefixRaw);if(!raw.includes('/')||extra.length||!Number.isInteger(prefix)||prefix<1||prefix>32)throw fail('Informe a rede no formato CIDR, por exemplo 192.168.250.0/24');const number=ipv4ToInt(ip),mask=prefix===32?0xffffffff:(0xffffffff<<(32-prefix))>>>0,network=(number&mask)>>>0,broadcast=(network+(2**(32-prefix)-1))>>>0;return{cidr:`${intToIpv4(network)}/${prefix}`,network:intToIpv4(network),prefix,broadcast:intToIpv4(broadcast),first:intToIpv4(prefix>=31?network:(network+1)>>>0),last:intToIpv4(prefix>=31?broadcast:(broadcast-1)>>>0),capacity:prefix>=31?2:Math.max(0,2**(32-prefix)-2),networkInt:network,broadcastInt:broadcast};}
export function cidrsOverlap(left,right){const a=typeof left==='string'?parseCidr(left):left,b=typeof right==='string'?parseCidr(right):right;return a.networkInt<=b.broadcastInt&&b.networkInt<=a.broadcastInt;}
export const addressInSubnet=(address,parsed)=>{const value=ipv4ToInt(address);return value>=parsed.networkInt&&value<=parsed.broadcastInt;};
const text=(value,max=240)=>String(value||'').trim().slice(0,max)||null;
export function normalizeSubnet(body){const parsed=parseCidr(body.cidr),gateway=text(body.gateway,45);if(gateway&&!addressInSubnet(gateway,parsed))throw fail('Gateway não pertence à rede informada');const vlan=body.vlanId==null||body.vlanId===''?null:Number(body.vlanId);if(vlan!==null&&(!Number.isInteger(vlan)||vlan<1||vlan>4094))throw fail('VLAN deve estar entre 1 e 4094');return{name:text(body.name,100)||parsed.cidr,cidr:parsed.cidr,network:parsed.network,prefix:parsed.prefix,gateway,vlanId:vlan,tenantId:text(body.tenantId,50),siteId:text(body.siteId,50),description:text(body.description,1000)};}
export async function listIpam(){const rows=await prisma.ipamSubnet.findMany({include:{tenant:{select:{id:true,name:true}},site:{select:{id:true,name:true}},addresses:{include:{asset:{select:{id:true,assetTag:true,name:true}}},orderBy:{address:'asc'}}},orderBy:[{tenantId:'asc'},{network:'asc'}]});return rows.map(row=>{const parsed=parseCidr(row.cidr);return{...row,summary:{capacity:parsed.capacity,used:row.addresses.length,free:Math.max(0,parsed.capacity-row.addresses.length),first:parsed.first,last:parsed.last,broadcast:parsed.broadcast}};});}
export async function normalizeAddress(body){const subnet=await prisma.ipamSubnet.findUnique({where:{id:String(body.subnetId||'')}});if(!subnet)throw fail('Rede não encontrada');const assetId=text(body.assetId,50),asset=assetId?await prisma.cmdbAsset.findUnique({where:{id:assetId},select:{id:true,tenantId:true,siteId:true}}):null;if(assetId&&!asset)throw fail('Ativo CMDB não encontrado');if(asset&&asset.tenantId!==subnet.tenantId)throw fail('O ativo não pertence ao mesmo cliente da rede');if(asset&&asset.siteId&&subnet.siteId&&asset.siteId!==subnet.siteId)throw fail('O ativo não pertence à mesma unidade da rede');const parsed=parseCidr(subnet.cidr),address=intToIpv4(ipv4ToInt(body.address));if(!addressInSubnet(address,parsed))throw fail('O IP não pertence à rede selecionada');if(parsed.prefix<31&&(address===parsed.network||address===parsed.broadcast))throw fail('Endereço de rede ou broadcast não pode ser reservado');return{subnetId:subnet.id,address,status:['assigned','reserved','dhcp','available'].includes(body.status)?body.status:'assigned',assetId,hostname:text(body.hostname,120),description:text(body.description,500)};}
