import prisma from '../database/client.js';

const fail=(message,statusCode=400)=>Object.assign(new Error(message),{statusCode});
export const ipv4ToInt=value=>{const parts=String(value||'').trim().split('.');if(parts.length!==4||parts.some(part=>!/^\d{1,3}$/.test(part)||Number(part)>255))throw fail('Endereço IPv4 inválido');return parts.reduce((total,part)=>(total*256+Number(part))>>>0,0)>>>0;};
export const intToIpv4=value=>[24,16,8,0].map(shift=>(value>>>shift)&255).join('.');
function ipv6ToBigInt(value){let raw=String(value||'').trim().toLowerCase();if(raw.includes('%'))raw=raw.split('%')[0];const groups=raw.split('::');if(groups.length>2)throw fail('Endereço IPv6 inválido');const left=groups[0]?groups[0].split(':'):[],right=groups[1]?groups[1].split(':'):[],expanded=groups.length===2?[...left,...Array(8-left.length-right.length).fill('0'),...right]:left;if(expanded.length!==8||expanded.some(item=>!/^[0-9a-f]{1,4}$/.test(item)))throw fail('Endereço IPv6 inválido');return expanded.reduce((total,item)=>(total<<16n)+BigInt(`0x${item}`),0n);}
function bigIntToIpv6(value){const groups=[];for(let shift=112n;shift>=0n;shift-=16n)groups.push(Number((value>>shift)&0xffffn).toString(16));let bestStart=-1,bestLength=0;for(let i=0;i<8;){if(groups[i]!=='0'){i++;continue;}let start=i;while(i<8&&groups[i]==='0')i++;if(i-start>bestLength){bestStart=start;bestLength=i-start;}}if(bestLength<2)return groups.join(':');return[groups.slice(0,bestStart).join(':'),groups.slice(bestStart+bestLength).join(':')].join('::').replace(/^:/,'').replace(/:$/,'');}
export function parseCidr(value){const raw=String(value||'').trim(),[ip,prefixRaw,...extra]=raw.split('/'),prefix=Number(prefixRaw);if(!raw.includes('/')||extra.length||!Number.isInteger(prefix))throw fail('Informe a rede no formato CIDR, por exemplo 192.168.250.0/24');if(ip.includes(':')){if(prefix<0||prefix>128)throw fail('Prefixo IPv6 deve estar entre 0 e 128');const number=ipv6ToBigInt(ip),mask=prefix===0?0n:((1n<<128n)-1n)^((1n<<BigInt(128-prefix))-1n),network=number&mask,broadcast=network+((1n<<BigInt(128-prefix))-1n),first=prefix>=127?network:network+1n,last=prefix>=127?broadcast:broadcast-1n;return{family:6,cidr:`${bigIntToIpv6(network)}/${prefix}`,network:bigIntToIpv6(network),prefix,broadcast:bigIntToIpv6(broadcast),first:bigIntToIpv6(first),last:bigIntToIpv6(last),capacity:prefix>=127?2:null,networkInt:network,broadcastInt:broadcast};}if(prefix<1||prefix>32)throw fail('Informe a rede no formato CIDR, por exemplo 192.168.250.0/24');const number=ipv4ToInt(ip),mask=prefix===32?0xffffffff:(0xffffffff<<(32-prefix))>>>0,network=(number&mask)>>>0,broadcast=(network+(2**(32-prefix)-1))>>>0;return{family:4,cidr:`${intToIpv4(network)}/${prefix}`,network:intToIpv4(network),prefix,broadcast:intToIpv4(broadcast),first:intToIpv4(prefix>=31?network:(network+1)>>>0),last:intToIpv4(prefix>=31?broadcast:(broadcast-1)>>>0),capacity:prefix>=31?2:Math.max(0,2**(32-prefix)-2),networkInt:network,broadcastInt:broadcast};}
export function cidrsOverlap(left,right){const a=typeof left==='string'?parseCidr(left):left,b=typeof right==='string'?parseCidr(right):right;if(a.family!==b.family)return false;return a.networkInt<=b.broadcastInt&&b.networkInt<=a.broadcastInt;}
export const addressInSubnet=(address,parsed)=>{try{const value=parsed.family===6?ipv6ToBigInt(address):ipv4ToInt(address);return value>=parsed.networkInt&&value<=parsed.broadcastInt;}catch{return false;}};
const text=(value,max=240)=>String(value||'').trim().slice(0,max)||null;
export function normalizeSubnet(body){const parsed=parseCidr(body.cidr),gateway=text(body.gateway,120);if(gateway&&!addressInSubnet(gateway,parsed))throw fail('Gateway não pertence à rede informada');const vlan=body.vlanId==null||body.vlanId===''?null:Number(body.vlanId);if(vlan!==null&&(!Number.isInteger(vlan)||vlan<1||vlan>4094))throw fail('VLAN deve estar entre 1 e 4094');return{name:text(body.name,100)||parsed.cidr,cidr:parsed.cidr,network:parsed.network,prefix:parsed.prefix,gateway,vlanId:vlan,tenantId:text(body.tenantId,50),siteId:text(body.siteId,50),description:text(body.description,1000)};}
export async function listIpam(){const rows=await prisma.ipamSubnet.findMany({include:{tenant:{select:{id:true,name:true}},site:{select:{id:true,name:true}},addresses:{include:{asset:{select:{id:true,assetTag:true,name:true}}},orderBy:{address:'asc'}}},orderBy:[{tenantId:'asc'},{network:'asc'}]});return rows.map(row=>{const parsed=parseCidr(row.cidr);return{...row,summary:{capacity:parsed.capacity,used:row.addresses.length,free:parsed.capacity===null?null:Math.max(0,parsed.capacity-row.addresses.length),first:parsed.first,last:parsed.last,broadcast:parsed.broadcast}};});}
export async function normalizeAddress(body){const subnet=await prisma.ipamSubnet.findUnique({where:{id:String(body.subnetId||'')}});if(!subnet)throw fail('Rede não encontrada');const assetId=text(body.assetId,50),asset=assetId?await prisma.cmdbAsset.findUnique({where:{id:assetId},select:{id:true,tenantId:true,siteId:true}}):null;if(assetId&&!asset)throw fail('Ativo CMDB não encontrado');if(asset&&asset.tenantId!==subnet.tenantId)throw fail('O ativo não pertence ao mesmo cliente da rede');if(asset&&asset.siteId&&subnet.siteId&&asset.siteId!==subnet.siteId)throw fail('O ativo não pertence à mesma unidade da rede');const parsed=parseCidr(subnet.cidr),raw=String(body.address||'').trim(),address=parsed.family===6?bigIntToIpv6(ipv6ToBigInt(raw)):intToIpv4(ipv4ToInt(raw));if(!addressInSubnet(address,parsed))throw fail('O IP não pertence à rede selecionada');if(parsed.prefix< (parsed.family===6?127:31)&&(address===parsed.network||address===parsed.broadcast))throw fail('Endereço de rede ou broadcast não pode ser reservado');return{subnetId:subnet.id,address,status:['assigned','reserved','dhcp','available'].includes(body.status)?body.status:'assigned',assetId,hostname:text(body.hostname,120),description:text(body.description,500)};}
