import crypto from 'node:crypto';
import prisma from '../database/client.js';
import { sshMikrotikExec } from '../tools/ssh-mikrotik.tool.js';
import { sshHuaweiVrpExec } from '../tools/ssh-huawei-vrp.tool.js';
import { sshCiscoIosExec } from '../tools/ssh-cisco-ios.tool.js';
import { cidrsOverlap, parseCidr } from './ipam.service.js';

const bad=(message,statusCode=400)=>Object.assign(new Error(message),{statusCode});
const supported={mikrotik:{exec:sshMikrotikExec,command:'/ip address print detail without-paging'},huawei_vrp:{exec:sshHuaweiVrpExec,command:'display ip interface brief'},cisco_ios:{exec:sshCiscoIosExec,command:'show running-config | section ^interface'}};
const vlanFrom=name=>{const match=String(name||'').match(/(?:vlan|vlanif|\.)(\d{1,4})/i),value=Number(match?.[1]);return value>=1&&value<=4094?value:null;};
export function parseDiscoveredAddresses(type,output){const source=String(output||'').replace(/\r/g,''),rows=[];if(type==='mikrotik'){for(const block of source.split(/\n(?=\s*\d+\s|\s*Flags:)/)){const address=block.match(/\baddress=(\d{1,3}(?:\.\d{1,3}){3}\/\d{1,2})/i)?.[1],name=block.match(/\binterface=([^\s]+)/i)?.[1]?.replaceAll('"','');if(address)rows.push({address,addressIp:address.split('/')[0],interfaceName:name||null,vlanId:vlanFrom(name),evidence:block.trim().slice(0,500)});}}else if(type==='huawei_vrp'){for(const line of source.split('\n')){const match=line.match(/^\s*(\S+)\s+(\d{1,3}(?:\.\d{1,3}){3}\/\d{1,2})\s+/);if(match)rows.push({interfaceName:match[1],address:match[2],addressIp:match[2].split('/')[0],vlanId:vlanFrom(match[1]),evidence:line.trim()});}}else if(type==='cisco_ios'){let name=null;for(const line of source.split('\n')){const int=line.match(/^interface\s+(\S+)/i);if(int){name=int[1];continue;}const ip=line.match(/^\s*ip address\s+(\d{1,3}(?:\.\d{1,3}){3})\s+(\d{1,3}(?:\.\d{1,3}){3})/i);if(ip){const bits=ip[2].split('.').map(Number).map(x=>x.toString(2).padStart(8,'0')).join(''),prefix=bits.indexOf('0')<0?32:bits.indexOf('0');rows.push({interfaceName:name,address:`${ip[1]}/${prefix}`,addressIp:ip[1],vlanId:vlanFrom(name),evidence:line.trim()});}}}return rows.filter(row=>{try{row.cidr=parseCidr(row.address).cidr;return true;}catch{return false;}});}
const keyFor=(assetId,row)=>crypto.createHash('sha256').update(`${assetId}:${row.address}:${row.interfaceName||''}`).digest('hex');
export async function detectIpamConflicts(){const subnets=await prisma.ipamSubnet.findMany({include:{addresses:{include:{asset:{select:{id:true,assetTag:true,name:true,tenantId:true,siteId:true}}}}},orderBy:{cidr:'asc'}}),conflicts=[];for(let i=0;i<subnets.length;i++){for(let j=i+1;j<subnets.length;j++){const left=subnets[i],right=subnets[j];if(left.tenantId===right.tenantId&&left.siteId===right.siteId&&cidrsOverlap(left.cidr,right.cidr))conflicts.push({type:'overlapping_subnets',severity:'high',message:`As redes ${left.cidr} e ${right.cidr} se sobrepõem`,subnets:[{id:left.id,cidr:left.cidr,name:left.name},{id:right.id,cidr:right.cidr,name:right.name}]});}}const seen=new Map();for(const subnet of subnets)for(const address of subnet.addresses){const key=address.address.toLowerCase(),previous=seen.get(key);if(previous)conflicts.push({type:'duplicate_address',severity:'critical',message:`O endereço ${address.address} está reservado em mais de uma rede`,addresses:[previous,{id:address.id,address:address.address,subnet:subnet.cidr,asset:address.asset?.name||null}]});else seen.set(key,{id:address.id,address:address.address,subnet:subnet.cidr,asset:address.asset?.name||null});if(address.asset&&address.asset.tenantId!==subnet.tenantId)conflicts.push({type:'tenant_mismatch',severity:'high',message:`O IP ${address.address} está vinculado a um ativo de outro cliente`,addressId:address.id,subnet:subnet.cidr,asset:address.asset.name});if(address.asset?.siteId&&subnet.siteId&&address.asset.siteId!==subnet.siteId)conflicts.push({type:'site_mismatch',severity:'medium',message:`O IP ${address.address} está vinculado a um ativo de outra unidade`,addressId:address.id,subnet:subnet.cidr,asset:address.asset.name});}return{total:conflicts.length,conflicts};}
export async function refreshIpamSuggestions(){const assets=await prisma.cmdbAsset.findMany({where:{device:{isActive:true,type:{in:Object.keys(supported)}}},include:{device:true}}),result={assets:assets.length,discovered:0,created:0,failed:[]};for(const asset of assets){try{const adapter=supported[asset.device.type],response=await adapter.exec({deviceId:asset.device.id,command:adapter.command});if(!response.success)throw bad(response.output||'Falha na consulta',502);for(const row of parseDiscoveredAddresses(asset.device.type,response.output)){result.discovered++;const exists=await prisma.ipamAddress.findFirst({where:{address:row.addressIp,subnet:{cidr:row.cidr}}});if(exists)continue;const originKey=keyFor(asset.id,row),current=await prisma.ipamReconciliationSuggestion.findUnique({where:{originKey}});if(current)continue;await prisma.ipamReconciliationSuggestion.create({data:{originKey,assetId:asset.id,address:row.addressIp,cidr:row.cidr,interfaceName:row.interfaceName,vlanId:row.vlanId,evidence:row.evidence}});result.created++;}}catch(error){result.failed.push({assetId:asset.id,name:asset.name,error:error.message});}}return result;}
export async function listIpamSuggestions(){return prisma.ipamReconciliationSuggestion.findMany({where:{status:'suggested'},include:{asset:{select:{id:true,assetTag:true,name:true,tenantId:true,siteId:true}}},orderBy:{createdAt:'desc'},take:500});}
export async function decideIpamSuggestion(id,approve,actor){const suggestion=await prisma.ipamReconciliationSuggestion.findUnique({where:{id},include:{asset:true}});if(!suggestion)throw bad('Sugestão não encontrada',404);if(suggestion.status!=='suggested')throw bad('Sugestão já analisada',409);if(!approve)return prisma.ipamReconciliationSuggestion.update({where:{id},data:{status:'ignored',reviewedBy:actor,reviewedAt:new Date()}});let subnet=await prisma.ipamSubnet.findUnique({where:{cidr:suggestion.cidr}});if(!subnet)subnet=await prisma.ipamSubnet.create({data:{name:suggestion.interfaceName?`${suggestion.asset.name} · ${suggestion.interfaceName}`:suggestion.cidr,cidr:suggestion.cidr,network:parseCidr(suggestion.cidr).network,prefix:parseCidr(suggestion.cidr).prefix,vlanId:suggestion.vlanId,tenantId:suggestion.asset.tenantId,siteId:suggestion.asset.siteId,description:'Descoberta pela reconciliação IPAM',createdBy:actor}});await prisma.ipamAddress.upsert({where:{subnetId_address:{subnetId:subnet.id,address:suggestion.address}},update:{assetId:suggestion.assetId,hostname:suggestion.asset.hostname||null,status:'assigned'},create:{subnetId:subnet.id,address:suggestion.address,status:'assigned',assetId:suggestion.assetId,hostname:suggestion.asset.hostname||null,description:`Interface ${suggestion.interfaceName||'não identificada'}`,createdBy:actor}});return prisma.ipamReconciliationSuggestion.update({where:{id},data:{status:'approved',reviewedBy:actor,reviewedAt:new Date()}});}
