import prisma from '../database/client.js';

export const LIFECYCLE_VENDORS=['MikroTik','Huawei','Cisco','Fortinet','Juniper'];
export const LIFECYCLE_TYPES=['software','hardware','license'];
export const LIFECYCLE_PRODUCT_STATUSES=['active','discontinued','unknown'];
export const LIFECYCLE_VENDOR_SOURCES=[
  {vendor:'MikroTik',title:'Catálogo oficial de produtos',url:'https://mikrotik.com/products',access:'public',guidance:'Localize o produto e confirme se a página exibe Discontinued.'},
  {vendor:'Huawei',title:'Info-Finder — Lifecycle Query',url:'https://info.support.huawei.com/info-finder/search-center/en/enterprise/eox',access:'public',guidance:'Pesquise pelo modelo e pela versão; registre EOM, EOFS e EOS publicados.'},
  {vendor:'Cisco',title:'End-of-Sale and End-of-Life Hub',url:'https://www.cisco.com/site/us/en/products/eol/index.html',access:'public',guidance:'Localize o PID exato e use as datas do boletim EOL correspondente.'},
  {vendor:'Fortinet',title:'Product Life Cycle',url:'https://support.fortinet.com/Information/ProductLifeCycle.aspx',access:'login',guidance:'Acesse o portal de suporte e consulte Hardware, Software ou Services.'},
  {vendor:'Juniper',title:'Product End of Life',url:'https://support.juniper.net/support/eol/',access:'public',guidance:'Escolha a família e confirme SKU, Last Order e End of Support.'}
];
const text=(value,max=255)=>String(value||'').trim().slice(0,max);
const date=value=>{if(!value)return null;const parsed=value instanceof Date?value:new Date(`${value}T12:00:00Z`);if(Number.isNaN(parsed.getTime()))throw Object.assign(new Error('Data inválida no catálogo'),{statusCode:400});return parsed;};
const pattern=value=>text(value,160)||'*';
const match=(value,rule)=>{if(!rule||rule==='*')return true;const escaped=rule.replace(/[.+?^${}()|[\]\\]/g,'\\$&').replaceAll('*','.*');return new RegExp(`^${escaped}$`,'i').test(String(value||''));};
export const LIFECYCLE_REVIEW_DAYS=Math.max(7,Math.min(365,Number(process.env.LIFECYCLE_CATALOG_REVIEW_DAYS)||90));
export function catalogVerificationStatus(entry,now=new Date()){if(!entry.lastVerifiedAt)return{status:'unverified',label:'Nunca verificado',daysSince:null};const daysSince=Math.floor((now-new Date(entry.lastVerifiedAt))/86400000);return{status:daysSince>=LIFECYCLE_REVIEW_DAYS?'stale':'current',label:daysSince>=LIFECYCLE_REVIEW_DAYS?`Revisão vencida (${daysSince} dias)`:`Verificado há ${daysSince} dia(s)`,daysSince};}

export function normalizeLifecycleCatalog(input){const vendor=text(input.vendor,80),product=text(input.product,140),lifecycleType=LIFECYCLE_TYPES.includes(input.lifecycleType)?input.lifecycleType:'software',productStatus=LIFECYCLE_PRODUCT_STATUSES.includes(input.productStatus)?input.productStatus:'unknown',modelPattern=pattern(input.modelPattern),versionPattern=pattern(input.versionPattern),sourceUrl=text(input.sourceUrl,1000);if(!vendor||!product)throw Object.assign(new Error('Informe fabricante e produto'),{statusCode:400});if(!/^https:\/\//i.test(sourceUrl))throw Object.assign(new Error('Informe a URL HTTPS da fonte oficial'),{statusCode:400});const releaseDate=date(input.releaseDate),endOfSaleDate=date(input.endOfSaleDate),endOfSupportDate=date(input.endOfSupportDate),lastVerifiedAt=date(input.lastVerifiedAt);if(endOfSaleDate&&endOfSupportDate&&endOfSupportDate<endOfSaleDate)throw Object.assign(new Error('Fim de suporte não pode ser anterior ao fim de venda'),{statusCode:400});return{vendor,product,lifecycleType,productStatus,modelPattern,versionPattern,releaseDate,endOfSaleDate,endOfSupportDate,sourceUrl,sourceTitle:text(input.sourceTitle,240)||null,lastVerifiedAt,notes:text(input.notes,2000)||null,isActive:input.isActive!==false};}
export async function listLifecycleCatalog(query={}){const rows=await prisma.lifecycleCatalogEntry.findMany({where:{...(query.vendor&&{vendor:String(query.vendor)}),...(query.lifecycleType&&{lifecycleType:String(query.lifecycleType)}),...(query.active!=='all'&&{isActive:true})},orderBy:[{vendor:'asc'},{product:'asc'},{versionPattern:'asc'}],take:1000});return rows.map(row=>({...row,verification:catalogVerificationStatus(row)}));}
export function matchLifecycleCatalog(asset,entries){const vendor=asset.manufacturer||asset.device?.manufacturer||'',model=asset.model||asset.device?.model||'',version=asset.device?.osVersion||'';return entries.filter(entry=>entry.isActive&&entry.vendor.toLowerCase()===vendor.toLowerCase()&&match(model,entry.modelPattern)&&match(version,entry.versionPattern)).sort((a,b)=>Number(Boolean(b.endOfSupportDate))-Number(Boolean(a.endOfSupportDate)))[0]||null;}
