import prisma from '../database/client.js';
import {matchLifecycleCatalog} from './lifecycle-catalog.service.js';

const DAY=86400000;
const remaining=(value,now)=>value?Math.ceil((new Date(value)-now)/DAY):null;
const rank=(rows,key)=>Object.entries(rows.reduce((acc,row)=>{const value=String(key(row)||'Não informado');acc[value]=(acc[value]||0)+1;return acc;},{})).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));

export function assessLifecycle(asset,now=new Date(),catalogMatch=null){
  const effectiveSupport=asset.supportUntil||catalogMatch?.endOfSupportDate||null,dates={warranty:remaining(asset.warrantyUntil,now),support:remaining(effectiveSupport,now),license:remaining(asset.licenseUntil,now)},known=Object.values(dates).filter(value=>value!==null),nearest=known.length?Math.min(...known):null,vulnerabilities=asset.device?.vulnerabilityFindings||[],critical=vulnerabilities.filter(row=>row.severity==='critical'||row.knownExploited).length,high=vulnerabilities.filter(row=>row.severity==='high').length;
  let status='healthy';if(nearest===null)status='unknown';else if(nearest<0)status='expired';else if(nearest<=7)status='critical';else if(nearest<=30)status='warning';else if(nearest<=90)status='attention';
  const discontinued=catalogMatch?.productStatus==='discontinued';let riskScore={healthy:0,unknown:20,attention:30,warning:55,critical:75,expired:90}[status]+Math.min(critical*12+high*5,25)+(discontinued?20:0);if(asset.criticality==='critical')riskScore+=10;else if(asset.criticality==='high')riskScore+=5;riskScore=Math.min(riskScore,100);
  const recommendation=status==='expired'?'Priorizar renovação, atualização ou substituição.':discontinued?'Produto oficialmente descontinuado; planejar substituição e confirmar suporte.':status==='critical'||status==='warning'?'Planejar ação dentro da janela de vencimento.':status==='unknown'?'Completar datas de garantia, suporte e licença.':critical||high?'Tratar vulnerabilidades e confirmar suporte da versão instalada.':'Manter acompanhamento do ciclo de vida.';
  return{status,riskScore,dates,nearestDays:nearest,vulnerabilities:{active:vulnerabilities.length,critical,high},recommendation,catalogMatch};
}

export async function lifecycleDashboard(filters={}){
  const where={status:{notIn:['retired','disposed']},...(filters.tenantId&&{tenantId:String(filters.tenantId)}),...(filters.manufacturer&&{manufacturer:String(filters.manufacturer)})},[assets,catalog]=await Promise.all([prisma.cmdbAsset.findMany({where,include:{tenant:{select:{id:true,name:true}},site:{select:{id:true,name:true}},device:{select:{id:true,name:true,hostname:true,type:true,manufacturer:true,model:true,osVersion:true,vulnerabilityFindings:{where:{status:{notIn:['resolved','accepted']}},select:{severity:true,knownExploited:true}}}},lifecycleAlerts:{where:{status:'active'},select:{id:true,type:true,severity:true,stage:true,title:true}}},orderBy:{name:'asc'}}),prisma.lifecycleCatalogEntry.findMany({where:{isActive:true}})]),rows=assets.map(asset=>{const catalogMatch=matchLifecycleCatalog(asset,catalog);return{...asset,lifecycle:assessLifecycle(asset,undefined,catalogMatch)}}),visible=filters.status?rows.filter(row=>row.lifecycle.status===filters.status):rows;
  return{rows:visible,summary:{assets:rows.length,expired:rows.filter(row=>row.lifecycle.status==='expired').length,critical:rows.filter(row=>row.lifecycle.status==='critical').length,warning:rows.filter(row=>row.lifecycle.status==='warning').length,attention:rows.filter(row=>row.lifecycle.status==='attention').length,unknown:rows.filter(row=>row.lifecycle.status==='unknown').length,withVulnerabilities:rows.filter(row=>row.lifecycle.vulnerabilities.active).length,highRisk:rows.filter(row=>row.lifecycle.riskScore>=70).length},byManufacturer:rank(rows,row=>row.manufacturer),byTenant:rank(rows,row=>row.tenant?.name||'Global'),filters:{manufacturers:[...new Set(assets.map(row=>row.manufacturer).filter(Boolean))].sort(),tenants:await prisma.tenant.findMany({where:{isActive:true},select:{id:true,name:true},orderBy:{name:'asc'}})}};
}
