import crypto from 'node:crypto';
import prisma from '../database/client.js';
import * as taskService from './task.service.js';

const stable=value=>JSON.stringify(value);
const nodeFields=['name','hostname','type','manufacturer','model','osVersion','group','tenantId','siteId'];
const linkFields=['sourceDeviceId','targetDeviceId','label','sourceInterface','targetInterface','bandwidthMbps','linkType','source'];
const pick=(row,fields)=>Object.fromEntries(fields.map(field=>[field,row[field]??null]));

export async function topologyState(){const[nodes,links]=await Promise.all([prisma.device.findMany({where:{isActive:true},select:Object.fromEntries(['id',...nodeFields].map(field=>[field,true])),orderBy:{id:'asc'}}),prisma.topologyLink.findMany({select:Object.fromEntries(['id',...linkFields].map(field=>[field,true])),orderBy:{id:'asc'}})]);return{nodes:nodes.map(row=>({id:row.id,...pick(row,nodeFields)})),links:links.map(row=>({id:row.id,...pick(row,linkFields)}))};}

export async function captureTopologySnapshot({source='manual',createdBy='system',baseline=false}={}){const state=await topologyState(),content=stable(state),sha256=crypto.createHash('sha256').update(content).digest('hex'),latest=await prisma.topologySnapshot.findFirst({orderBy:{createdAt:'desc'}});if(latest?.sha256===sha256&&!baseline)return latest;return prisma.$transaction(async tx=>{if(baseline)await tx.topologySnapshot.updateMany({where:{isBaseline:true},data:{isBaseline:false}});return tx.topologySnapshot.create({data:{source,content,sha256,nodeCount:state.nodes.length,linkCount:state.links.length,isBaseline:baseline,createdBy}})});}

const changed=(before,after,fields)=>fields.filter(field=>stable(before[field]??null)!==stable(after[field]??null)).map(field=>({field,before:before[field]??null,after:after[field]??null}));
export function compareTopologyStates(before,after){const compare=(left,right,fields)=>{const a=new Map(left.map(row=>[row.id,row])),b=new Map(right.map(row=>[row.id,row]));return{added:[...b.values()].filter(row=>!a.has(row.id)),removed:[...a.values()].filter(row=>!b.has(row.id)),changed:[...b.values()].filter(row=>a.has(row.id)).map(row=>({id:row.id,before:a.get(row.id),after:row,changes:changed(a.get(row.id),row,fields)})).filter(row=>row.changes.length)};};const nodes=compare(before.nodes,after.nodes,nodeFields),links=compare(before.links,after.links,linkFields);return{nodes,links,summary:{nodesAdded:nodes.added.length,nodesRemoved:nodes.removed.length,nodesChanged:nodes.changed.length,linksAdded:links.added.length,linksRemoved:links.removed.length,linksChanged:links.changed.length,total:nodes.added.length+nodes.removed.length+nodes.changed.length+links.added.length+links.removed.length+links.changed.length}};}
export async function compareTopologySnapshots(fromId,toId){const[from,to]=await Promise.all([prisma.topologySnapshot.findUnique({where:{id:fromId}}),prisma.topologySnapshot.findUnique({where:{id:toId}})]);if(!from||!to)throw Object.assign(new Error('Snapshot de topologia não encontrado'),{statusCode:404});return{from:{id:from.id,createdAt:from.createdAt,isBaseline:from.isBaseline,sha256:from.sha256},to:{id:to.id,createdAt:to.createdAt,isBaseline:to.isBaseline,sha256:to.sha256},...compareTopologyStates(JSON.parse(from.content),JSON.parse(to.content))};}
export async function listTopologySnapshots(){return prisma.topologySnapshot.findMany({select:{id:true,source:true,sha256:true,nodeCount:true,linkCount:true,isBaseline:true,createdBy:true,createdAt:true},orderBy:{createdAt:'desc'},take:100});}
export async function setTopologyBaseline(id){return prisma.$transaction(async tx=>{const row=await tx.topologySnapshot.findUnique({where:{id}});if(!row)throw Object.assign(new Error('Snapshot não encontrado'),{statusCode:404});await tx.topologySnapshot.updateMany({where:{isBaseline:true},data:{isBaseline:false}});return tx.topologySnapshot.update({where:{id},data:{isBaseline:true}})});}
export async function createTopologyChangeTask(fromId,toId,username){const comparison=await compareTopologySnapshots(fromId,toId);if(!comparison.summary.total)throw Object.assign(new Error('Não existem alterações para registrar'),{statusCode:400});const key=`topology:${comparison.from.sha256.slice(0,12)}:${comparison.to.sha256.slice(0,12)}`,existing=await prisma.task.findFirst({where:{incidentKey:key,status:{notIn:['closed','cancelled']}},select:{id:true,taskNumber:true}});if(existing)return{task:existing,comparison,existing:true};const text=`Alteração de topologia detectada. Equipamentos: +${comparison.summary.nodesAdded} -${comparison.summary.nodesRemoved} ~${comparison.summary.nodesChanged}. Conexões: +${comparison.summary.linksAdded} -${comparison.summary.linksRemoved} ~${comparison.summary.linksChanged}. Revise a comparação antes de aceitar o novo baseline.`;const task=await taskService.createTask({source:'topology_change',originalMessage:text,priority:comparison.summary.nodesRemoved+comparison.summary.linksRemoved?'high':'medium',workType:'configuration',incident:{incidentKey:key,incidentOpenedAt:new Date()}});await taskService.addTaskMessage(task.id,'system',`Task criada por ${username} a partir da comparação ${fromId} → ${toId}.`);return{task,comparison,existing:false};}
export async function captureAndDetectTopologyDrift(username='system'){const baseline=await prisma.topologySnapshot.findFirst({where:{isBaseline:true},orderBy:{createdAt:'desc'}}),current=await captureTopologySnapshot({source:'discovery',createdBy:username});if(!baseline||baseline.id===current.id)return{snapshot:current,comparison:null,task:null};const comparison=await compareTopologySnapshots(baseline.id,current.id);if(!comparison.summary.total)return{snapshot:current,comparison,task:null};const result=await createTopologyChangeTask(baseline.id,current.id,username);return{snapshot:current,comparison,task:result.task};}
