import { useEffect, useState } from 'react';
import { DatabaseBackup, Download, RefreshCw, RotateCcw, Save } from 'lucide-react';
import { api } from '../lib/api.js';
import { useToast } from '../contexts/ToastContext.jsx';

const size = bytes => bytes < 1024*1024 ? `${(bytes/1024).toFixed(1)} KB` : `${(bytes/1024/1024).toFixed(2)} MB`;
const typeName = value => ({manual:'Manual',automatic:'Automático','pre-restore':'Pré-restauração'}[value] || value);

export default function Backups(){
  const [items,setItems]=useState([]); const [config,setConfig]=useState({enabled:true,hour:2,retention:7}); const [busy,setBusy]=useState(false); const toast=useToast();
  const load=async()=>{try{const r=await api.getBackups();setItems(r.data);setConfig(r.config);}catch(e){toast(e.message,'error');}};
  useEffect(()=>{load();},[]);
  const create=async()=>{setBusy(true);try{await api.createBackup();await load();toast('Backup criado e validado','success');}catch(e){toast(e.message,'error');}finally{setBusy(false);}};
  const save=async()=>{setBusy(true);try{await api.updateBackupConfig(config);toast('Política de backup salva','success');}catch(e){toast(e.message,'error');}finally{setBusy(false);}};
  const download=async item=>{try{const blob=await api.downloadBackup(item.filename);const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=item.filename;link.click();URL.revokeObjectURL(link.href);}catch(e){toast(e.message,'error');}};
  const restore=async item=>{if(!window.confirm(`Restaurar ${item.filename}? O sistema voltará ao estado desse backup e será reiniciado.`))return;const password=window.prompt('Digite sua senha de administrador para confirmar:');if(!password)return;setBusy(true);try{const r=await api.restoreBackup(item.filename,password);toast(`${r.message} Cópia de segurança: ${r.safetyBackup}`,'success');setTimeout(()=>window.location.reload(),3000);}catch(e){toast(e.message,'error');setBusy(false);}};
  return <div><div className="page-header page-header-actions"><div><h2>Backup e restauração</h2><p>Proteção do banco de dados do NOC Agent</p></div><div style={{display:'flex',gap:8}}><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/>Atualizar</button><button className="btn btn-primary" onClick={create} disabled={busy}><DatabaseBackup size={15}/>Criar backup</button></div></div>
    <div className="card" style={{marginBottom:16}}><h3 style={{marginBottom:12}}>Backup automático</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}><div><label className="form-label">Habilitado</label><select className="form-select" value={String(config.enabled)} onChange={e=>setConfig({...config,enabled:e.target.value==='true'})}><option value="true">Sim</option><option value="false">Não</option></select></div><div><label className="form-label">Horário diário</label><input className="form-input" type="number" min="0" max="23" value={config.hour} onChange={e=>setConfig({...config,hour:Number(e.target.value)})}/></div><div><label className="form-label">Cópias automáticas mantidas</label><input className="form-input" type="number" min="1" max="90" value={config.retention} onChange={e=>setConfig({...config,retention:Number(e.target.value)})}/></div></div><button className="btn btn-primary" style={{marginTop:12}} onClick={save} disabled={busy}><Save size={15}/>Salvar política</button></div>
    <div className="table-container"><table><thead><tr><th>Data</th><th>Tipo</th><th>Arquivo</th><th>Tamanho</th><th>Integridade</th><th>Ações</th></tr></thead><tbody>{items.map(item=><tr key={item.filename}><td>{new Date(item.createdAt).toLocaleString('pt-BR')}</td><td>{typeName(item.type)}</td><td><code>{item.filename}</code></td><td>{size(item.size)}</td><td><span className="badge badge-success">Validado</span></td><td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn btn-secondary" onClick={()=>download(item)}><Download size={14}/>Baixar</button><button className="btn btn-secondary" onClick={()=>restore(item)} disabled={busy}><RotateCcw size={14}/>Restaurar</button></div></td></tr>)}{!items.length&&<tr><td colSpan="6"><div className="empty-state"><DatabaseBackup size={42}/><p>Nenhum backup disponível.</p></div></td></tr>}</tbody></table></div>
    <div className="card" style={{marginTop:16,borderColor:'var(--warning)'}}><strong>Segurança da restauração</strong><p style={{marginTop:6,color:'var(--text-secondary)',fontSize:'.85rem'}}>A integridade é verificada antes da restauração. O sistema cria automaticamente um backup pré-restauração e reinicia o serviço. Apenas administradores podem acessar esta página.</p></div>
  </div>;
}
