import { useEffect,useState } from 'react';
import { Bell,CheckCheck,Plus,RefreshCw,Save,Trash2,X } from 'lucide-react';
import { api } from '../lib/api.js';
import { useToast } from '../App.jsx';

const emptyRule=()=>({name:'',enabled:true,sortOrder:100,priorities:[],events:[],sources:[],deviceGroups:[],channels:['panel'],recipients:[],activeDays:[0,1,2,3,4,5,6],startTime:'00:00',endTime:'23:59',timezone:'America/Porto_Velho'});
const fmt=value=>new Date(value).toLocaleString('pt-BR');
const toggle=(array,value)=>array.includes(value)?array.filter(item=>item!==value):[...array,value];

export default function Notifications({isAdmin=false}){
  const [data,setData]=useState({rows:[],unread:0});const [rules,setRules]=useState([]);const [unread,setUnread]=useState(false);const [form,setForm]=useState(null);const [busy,setBusy]=useState('');const toast=useToast();
  const load=async()=>{try{setData((await api.getNotifications({unread})).data);if(isAdmin)setRules((await api.getNotificationRules()).data);}catch(e){toast(e.message,'error');}};
  useEffect(()=>{load();},[unread]);
  const mark=async id=>{try{await api.readNotification(id);setData(value=>({...value,rows:value.rows.map(row=>row.id===id?{...row,readAt:new Date().toISOString()}:row),unread:Math.max(0,value.unread-1)}));}catch(e){toast(e.message,'error');}};
  const save=async()=>{setBusy('save');try{const result=form.id?await api.updateNotificationRule(form.id,form):await api.createNotificationRule(form);toast(result.message,'success');setForm(null);await load();}catch(e){toast(e.message,'error');}finally{setBusy('');}};
  return <div><div className="page-header page-header-actions"><div><h2>Central de Notificações</h2><p>Alertas internos, entregas omnichannel e regras de roteamento</p></div><div><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/> Atualizar</button>{data.unread>0&&<button className="btn btn-secondary" onClick={async()=>{await api.readAllNotifications();await load();}}><CheckCheck size={15}/> Marcar todas</button>}{isAdmin&&<button className="btn btn-primary" onClick={()=>setForm(emptyRule())}><Plus size={15}/> Nova regra</button>}</div></div>
    <div className="notification-summary"><div className="stat-card"><Bell/><div><span className="stat-label">Não lidas</span><strong className="stat-value">{data.unread}</strong></div></div><label><input type="checkbox" checked={unread} onChange={e=>setUnread(e.target.checked)}/> Exibir somente não lidas</label></div>
    <div className="notification-layout"><section className="card notification-feed">{!data.rows.length?<div className="empty-state"><Bell/><p>Nenhuma notificação encontrada.</p></div>:data.rows.map(row=><article key={row.id} className={row.readAt?'read':'unread'} onClick={()=>!row.readAt&&mark(row.id)}><i/><div><header><strong>{row.title||row.event.replaceAll('_',' ')}</strong><span>{fmt(row.createdAt)}</span></header><p>{row.message||row.error||'Evento registrado no sistema.'}</p><footer><span>{row.priority||'informativo'}</span><span>{row.event}</span>{row.taskNumber&&<span>Task #{row.taskNumber}</span>}</footer></div></article>)}</section>
      {isAdmin&&<section className="card notification-rules"><h3>Regras ativas</h3>{!rules.length?<div className="empty-state"><p>Nenhuma regra personalizada. O roteamento padrão continua ativo.</p></div>:rules.map(rule=><article key={rule.id}><div><strong>{rule.name}</strong><span>Ordem {rule.sortOrder} · {rule.channels.join(', ')}</span><small>{rule.startTime}–{rule.endTime} · {rule.timezone}</small></div><div><button className="btn btn-ghost" onClick={()=>setForm({...rule})}>Editar</button><button className="btn btn-ghost" onClick={async()=>{if(confirm('Excluir esta regra?')){await api.deleteNotificationRule(rule.id);load();}}}><Trash2 size={14}/></button></div></article>)}</section>}</div>
    {form&&<div className="modal-overlay" onClick={()=>setForm(null)}><div className="modal notification-rule-modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><div><h3>{form.id?'Editar':'Nova'} regra</h3><p>Campos vazios significam qualquer valor</p></div><button className="btn btn-ghost" onClick={()=>setForm(null)}><X size={18}/></button></div><div className="notification-rule-body"><div className="form-row"><div className="form-group"><label className="form-label">Nome</label><input className="form-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="form-group"><label className="form-label">Ordem</label><input className="form-input" type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></div></div>
      <div className="form-group"><label className="form-label">Prioridades</label><div className="rule-options">{['low','medium','high','critical'].map(value=><label key={value}><input type="checkbox" checked={form.priorities.includes(value)} onChange={()=>setForm({...form,priorities:toggle(form.priorities,value)})}/>{value}</label>)}</div></div>
      <div className="form-group"><label className="form-label">Fontes</label><div className="rule-options">{['zabbix','dashboard','whatsapp','compliance'].map(value=><label key={value}><input type="checkbox" checked={form.sources.includes(value)} onChange={()=>setForm({...form,sources:toggle(form.sources,value)})}/>{value}</label>)}</div></div>
      <div className="form-group"><label className="form-label">Eventos, separados por vírgula</label><input className="form-input" value={form.events.join(',')} onChange={e=>setForm({...form,events:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})} placeholder="opened,sla_warning,resolved"/></div>
      <div className="form-group"><label className="form-label">Grupos de equipamentos, separados por vírgula</label><input className="form-input" value={form.deviceGroups.join(',')} onChange={e=>setForm({...form,deviceGroups:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></div>
      <div className="form-group"><label className="form-label">Canais</label><div className="rule-options">{['panel','telegram','whatsapp'].map(value=><label key={value}><input type="checkbox" checked={form.channels.includes(value)} onChange={()=>setForm({...form,channels:toggle(form.channels,value)})}/>{value}</label>)}</div></div>
      <div className="form-group"><label className="form-label">Chat IDs do Telegram, separados por vírgula</label><input className="form-input" value={form.recipients.join(',')} onChange={e=>setForm({...form,recipients:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></div>
      <div className="form-row"><div className="form-group"><label className="form-label">Início</label><input className="form-input" type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></div><div className="form-group"><label className="form-label">Fim</label><input className="form-input" type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></div><div className="form-group"><label className="form-label">Fuso</label><input className="form-input" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></div></div>
    </div><div className="modal-footer"><button className="btn btn-secondary" onClick={()=>setForm(null)}>Cancelar</button><button className="btn btn-primary" disabled={busy} onClick={save}><Save size={14}/> Salvar regra</button></div></div></div>}</div>;
}
