import {useEffect,useMemo,useState} from 'react';
import {CalendarClock,Clock,Plus,RefreshCw,Save,Trash2,UserRoundCheck,Users} from 'lucide-react';
import {api} from '../lib/api.js';
import {useToast} from '../App.jsx';

const DAYS=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const teamEmpty={name:'',description:'',timezone:'America/Porto_Velho',tenantId:''};
const memberEmpty={userId:'',telegramChatId:'',whatsappNumber:'',priority:100};
const shiftEmpty={userId:'',dayOfWeek:1,startTime:'08:00',endTime:'18:00'};
const overrideEmpty={userId:'',startsAt:'',endsAt:'',reason:''};
const date=value=>new Date(value).toLocaleString('pt-BR');

export default function OnCall(){
  const [data,setData]=useState({teams:[],users:[]}),[selected,setSelected]=useState(''),[teamForm,setTeamForm]=useState(teamEmpty),[member,setMember]=useState(memberEmpty),[shift,setShift]=useState(shiftEmpty),[override,setOverride]=useState(overrideEmpty),[busy,setBusy]=useState('');const toast=useToast();
  const load=async()=>{try{const result=(await api.getOnCall()).data;setData(result);setSelected(value=>result.teams.some(team=>team.id===value)?value:result.teams[0]?.id||'');}catch(error){toast(error.message,'error');}};
  useEffect(()=>{load();const timer=setInterval(load,60000);return()=>clearInterval(timer);},[]);
  const team=useMemo(()=>data.teams.find(item=>item.id===selected),[data,selected]);
  const act=async(name,fn,success)=>{setBusy(name);try{await fn();toast(success,'success');await load();}catch(error){toast(error.message,'error');}finally{setBusy('');}};
  const createTeam=e=>{e.preventDefault();act('team',()=>api.createOnCallTeam(teamForm),'Equipe criada');setTeamForm(teamEmpty);};
  const members=team?.members||[];
  return <div><div className="page-header page-header-actions"><div><h2>Plantão e Escala NOC</h2><p>Equipes, turnos, substituições e contatos acionados em incidentes críticos</p></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/> Atualizar</button></div>
    <section className="oncall-now">{data.teams.map(item=><article className="card" key={item.id}><div><UserRoundCheck size={20}/><span>{item.name}</span></div>{item.activeMembers.length?item.activeMembers.map(person=><strong key={person.id}>{person.name}</strong>):<strong className="oncall-empty">Sem plantonista agora</strong>}<small>{item.timezone}</small></article>)}</section>
    <div className="oncall-layout"><aside className="card oncall-teams"><h3><Users size={17}/> Equipes</h3>{data.teams.map(item=><button key={item.id} className={selected===item.id?'active':''} onClick={()=>setSelected(item.id)}><span>{item.name}</span><small>{item.enabled?'Ativa':'Desabilitada'} · {item.members.length} membro(s)</small></button>)}<form onSubmit={createTeam}><h4>Nova equipe</h4><input className="form-input" placeholder="Nome da equipe" value={teamForm.name} onChange={e=>setTeamForm({...teamForm,name:e.target.value})} required/><input className="form-input" placeholder="Descrição" value={teamForm.description} onChange={e=>setTeamForm({...teamForm,description:e.target.value})}/><input className="form-input" placeholder="Fuso horário" value={teamForm.timezone} onChange={e=>setTeamForm({...teamForm,timezone:e.target.value})}/><button className="btn btn-primary" disabled={busy==='team'}><Plus size={14}/> Criar</button></form></aside>
      <main className="oncall-workspace">{!team?<div className="card empty-state"><CalendarClock/><p>Crie uma equipe para configurar o plantão.</p></div>:<>
        <section className="card oncall-team-head"><div><h3>{team.name}</h3><p>{team.description||'Equipe de atendimento NOC'}</p></div><div><button className="btn btn-secondary" onClick={()=>act('toggle',()=>api.updateOnCallTeam(team.id,{enabled:!team.enabled}),team.enabled?'Equipe desabilitada':'Equipe habilitada')}>{team.enabled?'Desabilitar':'Habilitar'}</button><button className="btn btn-ghost" onClick={()=>confirm('Excluir equipe e toda a escala?')&&act('delete',()=>api.deleteOnCallTeam(team.id),'Equipe excluída')}><Trash2 size={15}/></button></div></section>
        <section className="card oncall-section"><h3><Users size={17}/> Plantonistas e contatos</h3><div className="oncall-records">{members.map(item=><article key={item.id}><div><strong>{item.user.name}</strong><small>{item.telegramChatId?`Telegram: ${item.telegramChatId}`:''}{item.whatsappNumber?` · WhatsApp: ${item.whatsappNumber}`:''}</small></div><span>Prioridade {item.priority}</span><button className="btn btn-ghost" onClick={()=>act('remove',()=>api.deleteOnCallMember(item.id),'Plantonista removido')}><Trash2 size={14}/></button></article>)}</div><form className="oncall-form" onSubmit={e=>{e.preventDefault();act('member',()=>api.saveOnCallMember(team.id,member),'Plantonista salvo');setMember(memberEmpty);}}><select className="form-select" value={member.userId} onChange={e=>setMember({...member,userId:e.target.value})} required><option value="">Selecione o usuário</option>{data.users.map(user=><option key={user.id} value={user.id}>{user.name} ({user.role})</option>)}</select><input className="form-input" placeholder="Chat ID Telegram" value={member.telegramChatId} onChange={e=>setMember({...member,telegramChatId:e.target.value})}/><input className="form-input" placeholder="WhatsApp com DDI" value={member.whatsappNumber} onChange={e=>setMember({...member,whatsappNumber:e.target.value})}/><input className="form-input" type="number" min="1" placeholder="Prioridade" value={member.priority} onChange={e=>setMember({...member,priority:Number(e.target.value)})}/><button className="btn btn-primary"><Save size={14}/> Salvar</button></form></section>
        <section className="card oncall-section"><h3><Clock size={17}/> Turnos recorrentes</h3><div className="oncall-records">{team.shifts.map(item=><article key={item.id}><div><strong>{item.user.name}</strong><small>{DAYS[item.dayOfWeek]} · {item.startTime}–{item.endTime}{item.startTime>item.endTime?' (vira o dia)':''}</small></div><button className="btn btn-ghost" onClick={()=>act('shift-delete',()=>api.deleteOnCallShift(item.id),'Turno removido')}><Trash2 size={14}/></button></article>)}</div><form className="oncall-form shift" onSubmit={e=>{e.preventDefault();act('shift',()=>api.createOnCallShift(team.id,shift),'Turno criado');}}><select className="form-select" value={shift.userId} onChange={e=>setShift({...shift,userId:e.target.value})} required><option value="">Plantonista</option>{members.map(item=><option key={item.userId} value={item.userId}>{item.user.name}</option>)}</select><select className="form-select" value={shift.dayOfWeek} onChange={e=>setShift({...shift,dayOfWeek:Number(e.target.value)})}>{DAYS.map((day,index)=><option key={day} value={index}>{day}</option>)}</select><input className="form-input" type="time" value={shift.startTime} onChange={e=>setShift({...shift,startTime:e.target.value})}/><input className="form-input" type="time" value={shift.endTime} onChange={e=>setShift({...shift,endTime:e.target.value})}/><button className="btn btn-primary"><Plus size={14}/> Adicionar</button></form></section>
        <section className="card oncall-section"><h3><CalendarClock size={17}/> Substituições temporárias</h3><div className="oncall-records">{team.overrides.map(item=><article key={item.id} className={team.activeOverrideId===item.id?'active':''}><div><strong>{item.user.name}</strong><small>{date(item.startsAt)} até {date(item.endsAt)}{item.reason?` · ${item.reason}`:''}</small></div>{team.activeOverrideId===item.id&&<span>Ativa agora</span>}<button className="btn btn-ghost" onClick={()=>act('override-delete',()=>api.deleteOnCallOverride(item.id),'Substituição removida')}><Trash2 size={14}/></button></article>)}</div><form className="oncall-form override" onSubmit={e=>{e.preventDefault();const payload={...override,startsAt:new Date(override.startsAt).toISOString(),endsAt:new Date(override.endsAt).toISOString()};act('override',()=>api.createOnCallOverride(team.id,payload),'Substituição criada');setOverride(overrideEmpty);}}><select className="form-select" value={override.userId} onChange={e=>setOverride({...override,userId:e.target.value})} required><option value="">Substituto</option>{members.map(item=><option key={item.userId} value={item.userId}>{item.user.name}</option>)}</select><input className="form-input" type="datetime-local" value={override.startsAt} onChange={e=>setOverride({...override,startsAt:e.target.value})} required/><input className="form-input" type="datetime-local" value={override.endsAt} onChange={e=>setOverride({...override,endsAt:e.target.value})} required/><input className="form-input" placeholder="Motivo" value={override.reason} onChange={e=>setOverride({...override,reason:e.target.value})}/><button className="btn btn-primary"><Plus size={14}/> Criar</button></form></section>
      </>}</main></div></div>;
}
