import { useEffect, useMemo, useState } from 'react';
import { Archive, CheckCircle2, Edit3, Eye, Library, Play, Plus, RefreshCw, RotateCcw, Save, Workflow, X } from 'lucide-react';
import { api } from '../lib/api.js';
import { useToast } from '../App.jsx';

const localId=()=>globalThis.crypto?.randomUUID?.()||`step-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const emptyStep=()=>({id:localId(),name:'',deviceType:'any',command:'',validation:'',rollback:'',continueOnError:false});
const emptyForm=()=>({name:'',description:'',category:'diagnostic',deviceType:'any',variables:[],steps:[emptyStep()]});
const labels={draft:'Rascunho',published:'Publicado',archived:'Arquivado',simulation:'Simulação',execution:'Execução',rollback:'Rollback',completed:'Concluída',failed:'Falhou',running:'Executando'};
const riskLabels={low:'Baixo risco',high:'Alto risco',critical:'Risco crítico'};
const approvalLabels={not_required:'Sem aprovação adicional',pending:'Aguardando outro administrador',approved:'Aprovado',rejected:'Rejeitado'};
const fmt=value=>value?new Date(value).toLocaleString('pt-BR'):'—';

export default function Runbooks({isAdmin=false,user}){
  const [runbooks,setRunbooks]=useState([]);
  const [devices,setDevices]=useState([]);
  const [deviceTypes,setDeviceTypes]=useState([]);
  const [selected,setSelected]=useState(null);
  const [form,setForm]=useState(null);
  const [deviceId,setDeviceId]=useState('');
  const [values,setValues]=useState({});
  const [simulation,setSimulation]=useState(null);
  const [templates,setTemplates]=useState([]);
  const [templateOpen,setTemplateOpen]=useState(false);
  const [busy,setBusy]=useState('');
  const toast=useToast();
  const load=async()=>{try{const [r,d,t]=await Promise.all([api.getRunbooks(),api.getDevices(),api.getDeviceTypes()]);setRunbooks(r.data);setDevices(d.data.filter(x=>x.isActive));setDeviceTypes(t.data.filter(x=>x.type!=='unifi_controller'));}catch(e){toast(e.message,'error');}};
  useEffect(()=>{load();},[]);
  const compatible=useMemo(()=>devices.filter(d=>!selected||selected.deviceType==='any'||selected.deviceType===d.type),[devices,selected]);
  const choose=item=>{setSelected(item);setDeviceId('');setValues(Object.fromEntries(item.variables.map(v=>[v.key,v.default||''])));setSimulation(null);};
  const mutate=(name,fn)=>async()=>{setBusy(name);try{const result=await fn();toast(result.message||'Operação concluída','success');setSelected(result.data);await load();}catch(e){toast(e.message,'error');}finally{setBusy('');}};
  const save=async()=>{setBusy('save');try{const result=form.id?await api.updateRunbook(form.id,form):await api.createRunbook(form);toast('Runbook salvo como rascunho','success');setForm(null);choose(result.data);await load();}catch(e){toast(e.message,'error');}finally{setBusy('');}};
  const runAction=async(name,fn)=>{setBusy(name);try{const result=await fn();toast(result.message||'Operação concluída','success');const fresh=(await api.getRunbook(selected.id)).data;setSelected(fresh);await load();return result;}catch(e){toast(e.message,'error');}finally{setBusy('');}};
  const simulate=async()=>{const result=await runAction('simulate',()=>api.simulateRunbook(selected.id,{deviceId,variables:values}));if(result)setSimulation(result.data);};
  const execute=()=>{if(!window.confirm('Executar este runbook no equipamento selecionado? Os comandos de alteração serão aplicados.'))return;runAction('execute',()=>api.executeRunbook(selected.id,{deviceId,variables:values}));};
  const rollback=id=>{if(!window.confirm('Executar o rollback desta execução?'))return;runAction('rollback',()=>api.rollbackRunbook(id));};
  const openTemplates=async()=>{setBusy('templates');try{setTemplates((await api.getRunbookTemplates()).data);setTemplateOpen(true);}catch(e){toast(e.message,'error');}finally{setBusy('');}};
  const importTemplate=async key=>{setBusy(`template:${key}`);try{const result=await api.importRunbookTemplate(key);toast(result.message,'success');setTemplateOpen(false);choose(result.data);await load();setForm(structuredClone(result.data));}catch(e){toast(e.message,'error');}finally{setBusy('');}};
  const review=approved=>{let reason='';if(!approved){reason=window.prompt('Informe o motivo da rejeição:')||'';if(!reason)return;}mutate(approved?'approve':'reject',()=>api.reviewRunbook(selected.id,approved,reason))();};
  const setVariable=(index,patch)=>setForm(v=>({...v,variables:v.variables.map((x,i)=>i===index?{...x,...patch}:x)}));
  const setStep=(index,patch)=>setForm(v=>({...v,steps:v.steps.map((x,i)=>i===index?{...x,...patch}:x)}));

  return <div>
    <div className="page-header page-header-actions"><div><h2>Catálogo de Runbooks</h2><p>Automações versionadas com simulação, validação, auditoria e rollback</p></div><div><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/> Atualizar</button>{isAdmin&&<button className="btn btn-secondary" disabled={busy==='templates'} onClick={openTemplates}><Library size={16}/> Biblioteca</button>}{isAdmin&&<button className="btn btn-primary" onClick={()=>setForm(emptyForm())}><Plus size={16}/> Novo runbook</button>}</div></div>
    <div className="runbook-layout">
      <section className="card runbook-catalog"><div className="runbook-section-title"><Workflow size={17}/><strong>Catálogo</strong><span>{runbooks.length}</span></div>
        {!runbooks.length?<div className="empty-state"><Workflow/><p>Nenhum runbook cadastrado.</p></div>:runbooks.map(item=><button key={item.id} className={`runbook-list-item ${selected?.id===item.id?'active':''}`} onClick={()=>choose(item)}><div><strong>{item.name}</strong><small>{item.category} · {item.deviceType} · v{item.version}</small></div><span className={`status-badge runbook-${item.status}`}>{labels[item.status]}</span></button>)}
      </section>
      <section className="card runbook-workspace">
        {!selected?<div className="empty-state"><Eye/><p>Selecione um runbook para visualizar e simular.</p></div>:<>
          <div className="runbook-detail-head"><div><h3>{selected.name}</h3><p>{selected.description}</p></div><div className="runbook-actions">{isAdmin&&selected.status!=='archived'&&<button className="btn btn-secondary" onClick={()=>setForm(structuredClone(selected))}><Edit3 size={14}/> Editar</button>}{isAdmin&&selected.status==='draft'&&(selected.riskLevel==='low'||selected.approvalStatus==='approved')&&<button className="btn btn-primary" disabled={busy} onClick={mutate('publish',()=>api.publishRunbook(selected.id))}><CheckCircle2 size={14}/> Publicar</button>}{isAdmin&&selected.status!=='archived'&&<button className="btn btn-ghost" disabled={busy} onClick={mutate('archive',()=>api.archiveRunbook(selected.id))}><Archive size={14}/> Arquivar</button>}</div></div>
          <div className="runbook-meta"><span>Versão <strong>{selected.version}</strong></span><span>{selected.steps.length} etapa(s)</span><span>{selected._count?.executions||0} execução(ões)</span><span className={`runbook-risk-${selected.riskLevel||'low'}`}>{riskLabels[selected.riskLevel]||'Baixo risco'}</span></div>
          {selected.riskLevel!=='low'&&<div className={`runbook-approval runbook-approval-${selected.approvalStatus}`}><div><strong>{approvalLabels[selected.approvalStatus]||selected.approvalStatus}</strong><span>Solicitado por {selected.approvalRequestedBy||'—'}{selected.approvedBy?` · revisado por ${selected.approvedBy}`:''}</span>{selected.rejectionReason&&<small>{selected.rejectionReason}</small>}</div>{isAdmin&&selected.status==='draft'&&<div className="runbook-actions">{selected.approvalStatus==='rejected'&&<button className="btn btn-secondary" disabled={busy} onClick={mutate('request',()=>api.requestRunbookApproval(selected.id))}>Solicitar novamente</button>}{selected.approvalStatus==='pending'&&<><button className="btn btn-secondary" disabled={busy} onClick={()=>review(false)}>Rejeitar</button><button className="btn btn-primary" disabled={busy||selected.approvalRequestedById===String(user?.sub||user?.id||user?.username)} onClick={()=>review(true)}><CheckCircle2 size={14}/> Aprovar</button></>}</div>}</div>}
          <div className="runbook-execute">
            <h4>Preparar execução</h4><div className="form-group"><label className="form-label">Equipamento</label><select className="form-select" value={deviceId} onChange={e=>{setDeviceId(e.target.value);setSimulation(null);}}><option value="">Selecione...</option>{compatible.map(d=><option key={d.id} value={d.id}>{d.name} · {d.hostname} · {d.type}</option>)}</select></div>
            {selected.variables.length>0&&<div className="runbook-variable-grid">{selected.variables.map(v=><div className="form-group" key={v.key}><label className="form-label">{v.label}{v.required?' *':''}</label><input className="form-input" value={values[v.key]||''} onChange={e=>{setValues(x=>({...x,[v.key]:e.target.value}));setSimulation(null);}} placeholder={v.key}/></div>)}</div>}
            <div className="runbook-actions"><button className="btn btn-secondary" disabled={!deviceId||busy} onClick={simulate}><Eye size={15}/> Simular</button>{isAdmin&&selected.status==='published'&&<button className="btn btn-primary" disabled={!simulation||busy} onClick={execute}><Play size={15}/> Executar simulação aprovada</button>}</div>
          </div>
          {simulation&&<div className="runbook-preview"><div className="runbook-section-title"><Eye size={16}/><strong>Prévia segura</strong><span>Nenhum comando executado</span></div>{simulation.renderedSteps.map((step,index)=><article key={step.id}><header><strong>{index+1}. {step.name}</strong><span className={`status-badge command-${step.commandType}`}>{step.commandType==='change'?'Alteração':'Consulta'}</span></header><pre>{step.command}</pre>{step.validation&&<><small>Validação</small><pre>{step.validation}</pre></>}{step.rollback&&<small>Rollback configurado</small>}</article>)}</div>}
          {selected.executions?.length>0&&<div className="runbook-history"><h4>Histórico recente</h4>{selected.executions.map(ex=><div key={ex.id}><div><strong>{labels[ex.mode]||ex.mode} · {ex.device?.name}</strong><small>{fmt(ex.createdAt)} · {ex.requestedBy}</small></div><span className={`status-badge runbook-${ex.status}`}>{labels[ex.status]||ex.status}</span>{isAdmin&&ex.mode==='execution'&&ex.status==='completed'&&ex.renderedSteps?.some(s=>s.rollback)&&<button className="btn btn-ghost" onClick={()=>rollback(ex.id)}><RotateCcw size={14}/> Rollback</button>}</div>)}</div>}
        </>}
      </section>
    </div>
    {templateOpen&&<div className="modal-overlay" onClick={()=>setTemplateOpen(false)}><div className="modal runbook-template-modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><div><h3>Biblioteca de modelos</h3><p>Importe um modelo seguro como rascunho e revise antes de publicar</p></div><button className="btn btn-ghost" onClick={()=>setTemplateOpen(false)}><X size={18}/></button></div><div className="runbook-template-grid">{templates.map(template=><article key={template.key}><div><Library size={18}/><span>{template.deviceType}</span></div><h4>{template.name}</h4><p>{template.description}</p><small>{template.steps.length} etapa(s) · {template.variables.length} variável(is) · somente consultas</small><button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>importTemplate(template.key)}>{busy===`template:${template.key}`?<span className="spinner"/>:<Plus size={14}/>} Importar e revisar</button></article>)}</div></div></div>}
    {form&&<div className="modal-overlay" onClick={()=>setForm(null)}><div className="modal runbook-editor" onClick={e=>e.stopPropagation()}><div className="modal-header"><div><h3>{form.id?'Editar':'Novo'} runbook</h3><p>Cada edição cria uma nova versão em rascunho</p></div><button className="btn btn-ghost" onClick={()=>setForm(null)}><X size={18}/></button></div><div className="runbook-editor-body">
      <div className="form-row"><div className="form-group"><label className="form-label">Nome</label><input className="form-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="form-group"><label className="form-label">Categoria</label><select className="form-select" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['diagnostic','network','security','monitoring','maintenance','custom'].map(x=><option key={x}>{x}</option>)}</select></div><div className="form-group"><label className="form-label">Tipo de equipamento</label><select className="form-select" value={form.deviceType} onChange={e=>setForm({...form,deviceType:e.target.value})}><option value="any">Todos os tipos</option>{deviceTypes.map(item=>{const count=devices.filter(device=>device.type===item.type).length;return <option key={item.type} value={item.type}>{item.label}{count?` · ${count} ativo(s)`:' · nenhum cadastrado'}</option>;})}</select><small className="form-help">Tipos sem equipamento podem ser usados no modelo, mas só poderão ser simulados após o cadastro.</small></div></div>
      <div className="form-group"><label className="form-label">Objetivo</label><textarea className="form-textarea" rows="2" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>
      <div className="runbook-editor-section"><div className="runbook-section-title"><strong>Variáveis</strong><button className="btn btn-ghost" onClick={()=>setForm(v=>({...v,variables:[...v.variables,{key:'',label:'',required:true,default:'',pattern:''}]}))}><Plus size={14}/> Adicionar</button></div>{form.variables.map((v,i)=><div className="runbook-variable-row" key={i}><input className="form-input" placeholder="chave" value={v.key} onChange={e=>setVariable(i,{key:e.target.value})}/><input className="form-input" placeholder="Rótulo" value={v.label} onChange={e=>setVariable(i,{label:e.target.value})}/><input className="form-input" placeholder="Valor padrão" value={v.default||''} onChange={e=>setVariable(i,{default:e.target.value})}/><label><input type="checkbox" checked={v.required!==false} onChange={e=>setVariable(i,{required:e.target.checked})}/> Obrigatória</label><button className="btn btn-ghost" onClick={()=>setForm(x=>({...x,variables:x.variables.filter((_,n)=>n!==i)}))}><X size={14}/></button></div>)}</div>
      <div className="runbook-editor-section"><div className="runbook-section-title"><strong>Etapas</strong><button className="btn btn-ghost" onClick={()=>setForm(v=>({...v,steps:[...v.steps,emptyStep()]}))}><Plus size={14}/> Adicionar</button></div>{form.steps.map((s,i)=><article className="runbook-step-editor" key={s.id}><div><strong>Etapa {i+1}</strong><button className="btn btn-ghost" disabled={form.steps.length===1} onClick={()=>setForm(x=>({...x,steps:x.steps.filter((_,n)=>n!==i)}))}><X size={14}/></button></div><input className="form-input" placeholder="Nome da etapa" value={s.name} onChange={e=>setStep(i,{name:e.target.value})}/><label className="form-label">Comando</label><textarea className="form-textarea runbook-code" rows="3" value={s.command} onChange={e=>setStep(i,{command:e.target.value})}/><div className="form-row"><div className="form-group"><label className="form-label">Comando de validação</label><textarea className="form-textarea runbook-code" rows="2" value={s.validation} onChange={e=>setStep(i,{validation:e.target.value})}/></div><div className="form-group"><label className="form-label">Comando de rollback</label><textarea className="form-textarea runbook-code" rows="2" value={s.rollback} onChange={e=>setStep(i,{rollback:e.target.value})}/></div></div></article>)}</div>
    </div><div className="modal-footer"><button className="btn btn-secondary" onClick={()=>setForm(null)}>Cancelar</button><button className="btn btn-primary" disabled={busy==='save'} onClick={save}><Save size={15}/> Salvar rascunho</button></div></div></div>}
  </div>;
}
