import{useEffect,useState}from'react';
import{ExternalLink,Plus,RadioTower,RefreshCw,Save,Send,Trash2}from'lucide-react';
import{api}from'../lib/api.js';import{useToast}from'../contexts/ToastContext.jsx';
const serviceEmpty={name:'',description:'',deviceId:'',automatic:true,manualStatus:'operational',sortOrder:100};
const incidentEmpty={serviceId:'',taskId:'',title:'',message:'',severity:'degraded',status:'investigating',scheduledAt:'',scheduledEndAt:''};
const labels={operational:'Operacional',degraded:'Degradado',partial_outage:'Indisponibilidade parcial',major_outage:'Indisponibilidade',maintenance:'Manutenção',investigating:'Investigando',identified:'Identificado',monitoring:'Monitorando',resolved:'Resolvido',scheduled:'Manutenção programada'};
export default function StatusPage(){
 const[data,setData]=useState({services:[],tasks:[],config:{}}),[devices,setDevices]=useState([]),[service,setService]=useState(serviceEmpty),[incident,setIncident]=useState(incidentEmpty),[updates,setUpdates]=useState({}),[busy,setBusy]=useState('');const toast=useToast();
 const load=async()=>{try{const[result,deviceResult]=await Promise.all([api.getStatusPageAdmin(),api.getDevices()]);setData(result.data);setDevices(deviceResult.data);}catch(e){toast(e.message,'error');}};
 useEffect(()=>{load();},[]);
 const act=async(key,fn,message)=>{setBusy(key);try{await fn();toast(message,'success');await load();}catch(e){toast(e.message,'error');}finally{setBusy('');}};
 return <div><div className="page-header page-header-actions"><div><h2>Status Page</h2><p>Comunicação pública segura de disponibilidade, incidentes e manutenções</p></div><div><a className="btn btn-secondary" href="/status" target="_blank"><ExternalLink size={15}/> Abrir página pública</a><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/> Atualizar</button></div></div>
 <section className="card status-config"><h3><RadioTower size={17}/> Identidade pública</h3><input className="form-input" value={data.config.status_page_title||''} placeholder="Título" onChange={e=>setData({...data,config:{...data.config,status_page_title:e.target.value}})}/><input className="form-input" value={data.config.status_page_description||''} placeholder="Descrição" onChange={e=>setData({...data,config:{...data.config,status_page_description:e.target.value}})}/><button className="btn btn-primary" onClick={()=>act('config',()=>api.saveStatusPageConfig({title:data.config.status_page_title,description:data.config.status_page_description}),'Identidade atualizada')}><Save size={14}/> Salvar</button></section>
 <div className="status-admin-grid"><section className="card status-editor"><h3>Serviços monitorados</h3><div className="status-service-list">{data.services.map(item=><article key={item.id}><i className={item.currentStatus}/><div><strong>{item.name}</strong><small>{labels[item.currentStatus]} · {item.automatic?'Automático':'Manual'}{item.device?` · ${item.device.name}`:''}</small></div><button className="btn btn-secondary" onClick={()=>act(`toggle-${item.id}`,()=>api.updateStatusService(item.id,{enabled:!item.enabled}),item.enabled?'Serviço ocultado':'Serviço publicado')}>{item.enabled?'Publicado':'Oculto'}</button><button className="btn btn-ghost" onClick={()=>confirm('Excluir este serviço e seus incidentes publicados?')&&act('delete',()=>api.deleteStatusService(item.id),'Serviço excluído')}><Trash2 size={14}/></button></article>)}</div><form onSubmit={e=>{e.preventDefault();act('service',()=>api.createStatusService(service),'Serviço criado');setService(serviceEmpty);}}><h4>Novo serviço</h4><input className="form-input" placeholder="Nome público" required value={service.name} onChange={e=>setService({...service,name:e.target.value})}/><input className="form-input" placeholder="Descrição pública" value={service.description} onChange={e=>setService({...service,description:e.target.value})}/><select className="form-select" value={service.deviceId} onChange={e=>setService({...service,deviceId:e.target.value})}><option value="">Sem equipamento vinculado</option>{devices.map(device=><option key={device.id} value={device.id}>{device.name}</option>)}</select><label><input type="checkbox" checked={service.automatic} onChange={e=>setService({...service,automatic:e.target.checked})}/> Estado automático pelas Tasks</label>{!service.automatic&&<select className="form-select" value={service.manualStatus} onChange={e=>setService({...service,manualStatus:e.target.value})}>{Object.entries(labels).slice(0,5).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select>}<button className="btn btn-primary"><Plus size={14}/> Criar serviço</button></form></section>
 <section className="card status-editor"><h3>Publicar incidente ou manutenção</h3><form onSubmit={e=>{e.preventDefault();const payload={...incident,...(incident.status==='scheduled'&&{scheduledAt:new Date(incident.scheduledAt).toISOString(),scheduledEndAt:new Date(incident.scheduledEndAt).toISOString()})};act('incident',()=>api.publishStatusIncident(payload),'Publicação criada');setIncident(incidentEmpty);}}><select className="form-select" required value={incident.serviceId} onChange={e=>setIncident({...incident,serviceId:e.target.value})}><option value="">Serviço afetado</option>{data.services.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="form-select" value={incident.taskId} onChange={e=>{const task=data.tasks.find(item=>item.id===e.target.value);setIncident({...incident,taskId:e.target.value,title:task?`Incidente em ${data.services.find(s=>s.id===incident.serviceId)?.name||'serviço'}`:incident.title});}}><option value="">Sem vínculo com Task</option>{data.tasks.map(task=><option key={task.id} value={task.id}>#{task.taskNumber} · {task.priority} · {task.status}</option>)}</select><select className="form-select" value={incident.status} onChange={e=>setIncident({...incident,status:e.target.value})}><option value="investigating">Incidente</option><option value="scheduled">Manutenção programada</option></select><select className="form-select" value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}><option value="degraded">Degradado</option><option value="partial_outage">Indisponibilidade parcial</option><option value="major_outage">Indisponibilidade total</option></select><input className="form-input" placeholder="Título público" required value={incident.title} onChange={e=>setIncident({...incident,title:e.target.value})}/><textarea className="form-input" placeholder="Mensagem pública sem IPs ou detalhes sensíveis" required value={incident.message} onChange={e=>setIncident({...incident,message:e.target.value})}/>{incident.status==='scheduled'&&<div className="form-row"><input className="form-input" type="datetime-local" required value={incident.scheduledAt} onChange={e=>setIncident({...incident,scheduledAt:e.target.value})}/><input className="form-input" type="datetime-local" required value={incident.scheduledEndAt} onChange={e=>setIncident({...incident,scheduledEndAt:e.target.value})}/></div>}<button className="btn btn-primary"><Send size={14}/> Publicar</button></form></section></div>
 <section className="status-incidents-admin">{data.services.flatMap(item=>item.incidents.map(value=>({...value,serviceName:item.name}))).map(item=><article className="card" key={item.id}><header><div><span className={item.severity}>{labels[item.status]}</span><h3>{item.title}</h3><small>{item.serviceName}</small></div></header><p>{item.message}</p><div className="status-update-form"><select className="form-select" value={updates[item.id]?.status||'identified'} onChange={e=>setUpdates({...updates,[item.id]:{...updates[item.id],status:e.target.value}})}><option value="identified">Causa identificada</option><option value="monitoring">Monitorando</option><option value="resolved">Resolvido</option></select><input className="form-input" placeholder="Atualização pública" value={updates[item.id]?.message||''} onChange={e=>setUpdates({...updates,[item.id]:{...updates[item.id],message:e.target.value}})}/><button className="btn btn-primary" onClick={()=>act(`update-${item.id}`,()=>api.updateStatusIncident(item.id,updates[item.id]||{}),'Atualização publicada')}><Send size={14}/> Atualizar</button></div></article>)}</section></div>;
}
