import { useEffect, useState } from 'react';
import { AlertTriangle, Download, ExternalLink, RefreshCw, Search, ShieldAlert, ShieldCheck, Wrench } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api } from '../lib/api.js';
import { useToast } from '../contexts/ToastContext.jsx';

const fmt=value=>value?new Date(value).toLocaleString('pt-BR'):'Nunca';

export default function Vulnerabilities(){
  const [data,setData]=useState({findings:[],devices:[],summary:{},severity:[],byManufacturer:[],byTenant:[],trend:[],tenants:[]}),[busy,setBusy]=useState(''),[scanAll,setScanAll]=useState({status:'idle'}),[filters,setFilters]=useState({days:'90',tenantId:''}),toast=useToast(),navigate=useNavigate();
  const load=async()=>{try{setData((await api.getVulnerabilities(Object.fromEntries(Object.entries(filters).filter(([,value])=>value)))).data);}catch(error){toast(error.message,'error');}};
  useEffect(()=>{load();},[filters.days,filters.tenantId]);
  useEffect(()=>{api.getVulnerabilityScanAllStatus().then(row=>setScanAll(row.data)).catch(()=>{});},[]);
  useEffect(()=>{if(scanAll.status!=='running')return;const timer=setInterval(async()=>{const state=(await api.getVulnerabilityScanAllStatus()).data;setScanAll(state);if(state.status==='completed'){toast(`Análise concluída: ${state.completed} sucesso, ${state.failed} falha(s).`,'success');load();}},3000);return()=>clearInterval(timer);},[scanAll.status]);
  const scan=async device=>{setBusy(device.id);try{const result=await api.scanDeviceVulnerabilities(device.id);toast(result.message,'success');await load();}catch(error){toast(error.message,'error');}finally{setBusy('');}};
  const startAll=async()=>{try{const result=await api.scanAllVulnerabilities();setScanAll(result.data);toast(result.message,'success');}catch(error){toast(error.message,'error');}};
  const decide=async(item,action)=>{let resolution='';if(action==='resolve'){resolution=window.prompt('Informe a correção ou mitigação aplicada:')||'';if(!resolution.trim())return;}if(action==='accept'&&!window.confirm('Aceitar formalmente este risco?'))return;try{await api.decideVulnerability(item.id,action,resolution);toast('Vulnerabilidade atualizada.','success');await load();}catch(error){toast(error.message,'error');}};
  const planRemediation=item=>{
    const device=item.device,reference=`${item.cveId}${item.cvssScore?` (CVSS ${item.cvssScore})`:''}${item.knownExploited?' — CISA KEV':''}`;
    sessionStorage.setItem('noc_change_draft',JSON.stringify({
      title:`Correção de ${item.cveId} em ${device.name}`,
      description:`Remediar ${reference} identificada em ${device.name} (${device.hostname}). ${item.description}`,
      reason:`Reduzir a exposição de segurança associada a ${item.cveId} e manter o equipamento em versão suportada.`,
      impact:'Pode haver indisponibilidade temporária durante atualização, reinicialização ou aplicação da mitigação. Validar dependências no CMDB antes da execução.',
      executionPlan:`1. Confirmar versão, configuração e conectividade atuais.\n2. Capturar backup antes da mudança.\n3. Consultar o boletim do fabricante e preparar atualização ou mitigação para ${item.cveId}.\n4. Aplicar somente durante a janela aprovada.\n5. Registrar comandos, versão final e evidências.`,
      validationPlan:'1. Confirmar acesso e serviços do equipamento.\n2. Validar versão e configuração final.\n3. Executar Compliance e nova análise de vulnerabilidades.\n4. Confirmar que monitoração e tráfego estão normais.',
      rollbackPlan:'1. Interromper a execução se houver perda de conectividade ou serviço.\n2. Restaurar a configuração capturada antes da mudança.\n3. Reverter versão ou mitigação conforme procedimento do fabricante.\n4. Validar novamente conectividade e monitoração.',
      changeType:item.knownExploited||item.severity==='critical'?'emergency':'normal',deviceIds:[device.id],taskId:item.taskId||null,vulnerabilityId:item.id,
    }));
    navigate('/changes');
  };
  const active=data.findings.filter(row=>!['resolved','accepted'].includes(row.status)),maxRank=Math.max(1,...(data.byManufacturer||[]).map(row=>row.count)),maxTrend=Math.max(1,...(data.trend||[]).flatMap(row=>[row.opened,row.resolved]));
  const download=async format=>{setBusy(`export-${format}`);try{const file=await api.downloadVulnerabilityReport(format,Object.fromEntries(Object.entries(filters).filter(([,value])=>value))),url=URL.createObjectURL(file.blob),link=document.createElement('a');link.href=url;link.download=file.filename;link.click();URL.revokeObjectURL(url);}catch(error){toast(error.message,'error');}finally{setBusy('');}};
  return <div>
    <div className="page-header page-header-actions"><div><h2>Gestão de Vulnerabilidades</h2><p>Visão executiva, exposição técnica e ciclo controlado de remediação</p></div><div><button className="btn btn-secondary" onClick={()=>download('csv')} disabled={busy==='export-csv'}><Download size={15}/>CSV</button><button className="btn btn-secondary" onClick={()=>download('pdf')} disabled={busy==='export-pdf'}><Download size={15}/>PDF</button><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/>Atualizar</button><button className="btn btn-primary" disabled={scanAll.status==='running'} onClick={startAll}><Search size={15}/>{scanAll.status==='running'?`${scanAll.completed}/${scanAll.total}`:'Analisar todos'}</button></div></div>
    <div className="card vulnerability-filters"><div><label className="form-label">Período executivo</label><select className="form-select" value={filters.days} onChange={event=>setFilters({...filters,days:event.target.value})}><option value="30">30 dias</option><option value="90">90 dias</option><option value="180">180 dias</option><option value="365">12 meses</option></select></div>{Boolean(data.tenants?.length)&&<div><label className="form-label">Cliente</label><select className="form-select" value={filters.tenantId} onChange={event=>setFilters({...filters,tenantId:event.target.value})}><option value="">Todos os clientes</option>{data.tenants.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></div>}</div>
    <div className="stats-grid">{[['Vulnerabilidades ativas',data.summary.active||0,ShieldAlert],['Críticas',data.summary.critical||0,AlertTriangle],['Exploradas (KEV)',data.summary.kev||0,ShieldAlert],['SLA vencido',data.summary.overdue||0,AlertTriangle],['Novas no período',data.summary.newInPeriod||0,Search],['Resolvidas no período',data.summary.resolvedInPeriod||0,ShieldCheck],['Tempo médio de correção',data.summary.meanRemediationHours===null?'—':`${data.summary.meanRemediationHours}h`,RefreshCw],['Com RFC',`${data.summary.withChange||0}/${active.length}`,Wrench]].map(([label,value,Icon])=><div className="stat-card" key={label}><div className="stat-icon"><Icon size={20}/></div><div><div className="stat-value">{value}</div><div className="stat-label">{label}</div></div></div>)}</div>
    <div className="vulnerability-executive-grid">
      <section className="card"><h3>Exposição por fabricante</h3><div className="vulnerability-ranking">{data.byManufacturer?.map(row=><div key={row.name}><span>{row.name}</span><div><i style={{width:`${Math.max(4,row.count/maxRank*100)}%`}}/></div><strong>{row.count}</strong></div>)}{!data.byManufacturer?.length&&<small>Sem exposição ativa.</small>}</div></section>
      <section className="card"><h3>Evolução semanal</h3><div className="vulnerability-trend">{data.trend?.map(row=><div key={row.period}><span>{new Date(`${row.period}T00:00:00Z`).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</span><div title={`${row.opened} novas`}><i className="opened" style={{height:`${Math.max(3,row.opened/maxTrend*72)}px`}}/></div><div title={`${row.resolved} resolvidas`}><i className="resolved" style={{height:`${Math.max(3,row.resolved/maxTrend*72)}px`}}/></div><small>{row.opened}/{row.resolved}</small></div>)}{!data.trend?.length&&<small>Sem movimentação no período.</small>}</div><div className="vulnerability-legend"><span><i className="opened"/>Novas</span><span><i className="resolved"/>Resolvidas</span></div></section>
      <section className="card"><h3>Exposição por cliente</h3><div className="vulnerability-ranking">{data.byTenant?.map(row=><div key={row.name}><span>{row.name}</span><div><i style={{width:`${Math.max(4,row.count/Math.max(1,...data.byTenant.map(item=>item.count))*100)}%`}}/></div><strong>{row.count}</strong></div>)}{!data.byTenant?.length&&<small>Sem exposição ativa.</small>}</div></section>
    </div>
    <div className="card vulnerability-devices"><h3>Cobertura do inventário</h3><div className="table-container"><table><thead><tr><th>Equipamento</th><th>Versão</th><th>Correlação</th><th>Última análise</th><th></th></tr></thead><tbody>{data.devices.map(device=><tr key={device.id}><td><strong>{device.name}</strong><br/><small>{device.hostname} · {device.type}</small></td><td>{device.osVersion||'Não informada'}</td><td>{device.cpe?<code>{device.cpe}</code>:<span className="status-badge status-pending">Inventário insuficiente</span>}</td><td>{fmt(device.lastScan?.completedAt)}{device.lastScan?.error&&<small className="vulnerability-error">{device.lastScan.error}</small>}</td><td><button className="btn btn-primary btn-sm" disabled={!device.cpe||busy===device.id||scanAll.status==='running'} onClick={()=>scan(device)}><Search size={14}/>{busy===device.id?'Analisando...':'Analisar'}</button></td></tr>)}</tbody></table></div></div>
    <div className="card vulnerability-findings"><h3>Vulnerabilidades encontradas</h3>{!data.findings.length?<div className="empty-state"><ShieldCheck size={36}/><p>Nenhuma vulnerabilidade registrada.</p></div>:<div className="table-container"><table><thead><tr><th>CVE</th><th>Equipamento</th><th>Risco</th><th>Descrição</th><th>Status</th><th>Ações</th></tr></thead><tbody>{data.findings.map(item=><tr key={item.id}><td><a href={item.sourceUrl} target="_blank" rel="noreferrer"><strong>{item.cveId}</strong><ExternalLink size={12}/></a>{item.knownExploited&&<span className="kev-badge">CISA KEV</span>}</td><td>{item.device.name}<br/><small>{item.device.osVersion}</small></td><td><span className={`status-badge vulnerability-${item.severity}`}>{item.severity}</span><br/><small>CVSS {item.cvssScore??'—'}</small></td><td className="vulnerability-description">{item.description}</td><td><span className={`status-badge vulnerability-status-${item.status}`}>{item.status}</span></td><td><div className="table-actions">{!['resolved','accepted'].includes(item.status)&&<button className="btn btn-secondary btn-sm" onClick={()=>planRemediation(item)}><Wrench size={13}/>Planejar correção</button>}{item.status==='open'&&<button className="btn btn-secondary btn-sm" onClick={()=>decide(item,'acknowledge')}>Reconhecer</button>}{!['resolved','accepted'].includes(item.status)&&<button className="btn btn-primary btn-sm" onClick={()=>decide(item,'resolve')}>Resolver</button>}{!['resolved','accepted'].includes(item.status)&&<button className="btn btn-ghost btn-sm" onClick={()=>decide(item,'accept')}>Aceitar risco</button>}</div></td></tr>)}</tbody></table></div>}</div>
  </div>;
}
